// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_INPUTMAPPINGDESCRIPTION_DEVICEANDAXISSEPERATOR              48300
#define IDGS_INPUTMAPPINGDESCRIPTION_DEVICEANDBUTTONSEPERATOR            48301
#define IDGS_INPUTMAPPINGDESCRIPTION_HOLDBUTTONSSEPERATOR                48302
#define IDGS_INPUTMAPPINGDESCRIPTION_HOLDBUTTONSSTART                    48303
#define IDGS_INPUTMAPPINGDESCRIPTION_KEYBOARDDESCRIPTION                 48304
#define IDGS_INPUTMAPPINGDESCRIPTION_MOUSEAXIS0                          48305
#define IDGS_INPUTMAPPINGDESCRIPTION_MOUSEAXIS1                          48306
#define IDGS_INPUTMAPPINGDESCRIPTION_MOUSEAXIS2                          48307
#define IDGS_INPUTMAPPINGDESCRIPTION_MOUSEBUTTON                         48308
#define IDGS_INPUTMAPPINGDESCRIPTION_MOUSEDESCRIPTION                    48309
#define IDGS_INPUTMAPPINGDESCRIPTION_NOTMAPPED                           48310
