// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_ISINPUTMAPPINGVALID_AXISNOTVALID                            48400
#define IDGS_ISINPUTMAPPINGVALID_HOLDBUTTONNOTVALID                      48401
#define IDGS_ISINPUTMAPPINGVALID_KEYBOARDHASNOAXES                       48402
#define IDGS_ISINPUTMAPPINGVALID_KEYNUMBERNOTSUPPORTED                   48403
#define IDGS_ISINPUTMAPPINGVALID_MOUSEAXISNUMBERNOTSUPPORTED             48404
#define IDGS_ISINPUTMAPPINGVALID_MOUSEBUTTONNUMBERNOTSUPPORTED           48405
#define IDGS_ISINPUTMAPPINGVALID_NORMOREKEYBOARDSNOTSUPPORTED            48406
#define IDGS_ISINPUTMAPPINGVALID_NORMOREMICENOTSUPPORTED                 48407
#define IDGS_ISINPUTMAPPINGVALID_PRIMARYBUTTONNOTVALID                   48408
