// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_SCREENCURSORUSERINPUT_CURSORX_DESCRIPTION                   48500
#define IDGS_SCREENCURSORUSERINPUT_CURSORX_NAME                          48501
#define IDGS_SCREENCURSORUSERINPUT_CURSORY_DESCRIPTION                   48502
#define IDGS_SCREENCURSORUSERINPUT_CURSORY_NAME                          48503
