// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN02B                              51800
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN03B                              51801
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN04                               51802
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN04B                              51803
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN05                               51804
#define IDGS_TPCREWSPEECHPRRFC_AICAPTAIN05B                              51805
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN01                                 51806
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN02                                 51807
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN03                                 51808
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN04                                 51809
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN05                                 51810
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN06                                 51811
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN07                                 51812
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN08                                 51813
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN09                                 51814
#define IDGS_TPCREWSPEECHPRRFC_CAPTAIN10                                 51815
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE01                               51816
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE01B                              51817
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE02                               51818
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE02B                              51819
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE03                               51820
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE04                               51821
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE04B                              51822
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE05                               51823
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE06                               51824
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE06B                              51825
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE07                               51826
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE08                               51827
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE09                               51828
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE11                               51829
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE12                               51830
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE12B                              51831
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE13                               51832
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE14                               51833
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE14B                              51834
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE15                               51835
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE15B                              51836
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE16                               51837
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE16B                              51838
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE18                               51839
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE19                               51840
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE20                               51841
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE20B                              51842
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE21                               51843
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE22                               51844
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE23                               51845
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE24                               51846
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE26                               51847
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE26B                              51848
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE27                               51849
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE27B                              51850
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE28                               51851
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE28B                              51852
#define IDGS_TPCREWSPEECHPRRFC_FIRSTMATE29                               51853
#define IDGS_TPCREWSPEECHPRRFC_RIGGER03                                  51854
#define IDGS_TPCREWSPEECHPRRFC_RIGGER03B                                 51855
#define IDGS_TPCREWSPEECHPRRFC_RIGGER04                                  51856
#define IDGS_TPCREWSPEECHPRRFC_RIGGER04B                                 51857
#define IDGS_TPCREWSPEECHPRRFC_RIGGER05                                  51858
#define IDGS_TPCREWSPEECHPRRFC_RIGGER06                                  51859
