// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN02B                              52000
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN03B                              52001
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN04                               52002
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN04B                              52003
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN05                               52004
#define IDGS_TPCREWSPEECHRORFC_AICAPTAIN05B                              52005
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN01                                 52006
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN02                                 52007
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN03                                 52008
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN04                                 52009
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN05                                 52010
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN06                                 52011
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN07                                 52012
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN08                                 52013
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN09                                 52014
#define IDGS_TPCREWSPEECHRORFC_CAPTAIN10                                 52015
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE01                               52016
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE01B                              52017
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE02                               52018
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE02B                              52019
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE03                               52020
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE04                               52021
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE04B                              52022
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE05                               52023
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE06                               52024
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE06B                              52025
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE07                               52026
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE08                               52027
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE09                               52028
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE11                               52029
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE12                               52030
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE12B                              52031
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE13                               52032
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE14                               52033
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE14B                              52034
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE15                               52035
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE15B                              52036
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE16                               52037
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE16B                              52038
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE18                               52039
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE19                               52040
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE20                               52041
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE20B                              52042
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE21                               52043
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE22                               52044
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE23                               52045
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE24                               52046
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE26                               52047
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE26B                              52048
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE27                               52049
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE27B                              52050
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE28                               52051
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE28B                              52052
#define IDGS_TPCREWSPEECHRORFC_FIRSTMATE29                               52053
#define IDGS_TPCREWSPEECHRORFC_RIGGER03                                  52054
#define IDGS_TPCREWSPEECHRORFC_RIGGER03B                                 52055
#define IDGS_TPCREWSPEECHRORFC_RIGGER04                                  52056
#define IDGS_TPCREWSPEECHRORFC_RIGGER04B                                 52057
#define IDGS_TPCREWSPEECHRORFC_RIGGER05                                  52058
#define IDGS_TPCREWSPEECHRORFC_RIGGER06                                  52059
