// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER01                               50900
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER01B                              50901
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER02                               50902
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER02B                              50903
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER03                               50904
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER03B                              50905
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER04                               50906
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER05                               50907
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER06                               50908
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER06B                              50909
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER07                               50910
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER07B                              50911
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER08                               50912
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER08B                              50913
#define IDGS_TPCREWSPEECHHMGEHS_ENGINEER09                               50914
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER01                                 50915
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER02                                 50916
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER03                                 50917
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER04                                 50918
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER05                                 50919
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER06                                 50920
#define IDGS_TPCREWSPEECHHMGEHS_GUNNER06B                                50921
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN01                               50922
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN01B                              50923
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN02                               50924
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN02B                              50925
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN03                               50926
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN03B                              50927
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN04                               50928
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN04B                              50929
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN06                               50930
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN06B                              50931
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN07                               50932
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN07B                              50933
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN08                               50934
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN08B                              50935
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN09                               50936
#define IDGS_TPCREWSPEECHHMGEHS_HELMSMAN09B                              50937
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER01                                50938
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER02                                50939
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER03                                50940
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER05                                50941
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER06                                50942
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER06B                               50943
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER07                                50944
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER08                                50945
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER09                                50946
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER10                                50947
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER11                                50948
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER12                                50949
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER13                                50950
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER14                                50951
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER15                                50952
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER16                                50953
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER17                                50954
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER18                                50955
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER19                                50956
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER20                                50957
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER21                                50958
#define IDGS_TPCREWSPEECHHMGEHS_SPOTTER22                                50959
