// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER01                               50100
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER01B                              50101
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER02                               50102
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER02B                              50103
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER03                               50104
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER03B                              50105
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER04                               50106
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER05                               50107
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER06                               50108
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER06B                              50109
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER07                               50110
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER07B                              50111
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER08                               50112
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER08B                              50113
#define IDGS_TPCREWSPEECHDEGEHS_ENGINEER09                               50114
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER01                                 50115
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER02                                 50116
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER03                                 50117
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER04                                 50118
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER05                                 50119
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER06                                 50120
#define IDGS_TPCREWSPEECHDEGEHS_GUNNER06B                                50121
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN01                               50122
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN01B                              50123
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN02                               50124
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN02B                              50125
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN03                               50126
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN03B                              50127
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN04                               50128
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN04B                              50129
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN06                               50130
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN06B                              50131
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN07                               50132
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN07B                              50133
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN08                               50134
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN08B                              50135
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN09                               50136
#define IDGS_TPCREWSPEECHDEGEHS_HELMSMAN09B                              50137
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER01                                50138
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER02                                50139
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER03                                50140
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER05                                50141
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER06                                50142
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER06B                               50143
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER07                                50144
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER08                                50145
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER09                                50146
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER10                                50147
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER11                                50148
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER12                                50149
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER13                                50150
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER14                                50151
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER15                                50152
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER16                                50153
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER17                                50154
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER18                                50155
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER19                                50156
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER20                                50157
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER21                                50158
#define IDGS_TPCREWSPEECHDEGEHS_SPOTTER22                                50159
