// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER01                               52100
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER01B                              52101
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER02                               52102
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER02B                              52103
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER03                               52104
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER03B                              52105
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER04                               52106
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER05                               52107
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER06                               52108
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER06B                              52109
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER07                               52110
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER07B                              52111
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER08                               52112
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER08B                              52113
#define IDGS_TPCREWSPEECHTUGEHS_ENGINEER09                               52114
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER01                                 52115
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER02                                 52116
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER03                                 52117
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER04                                 52118
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER05                                 52119
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER06                                 52120
#define IDGS_TPCREWSPEECHTUGEHS_GUNNER06B                                52121
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN01                               52122
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN01B                              52123
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN02                               52124
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN02B                              52125
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN03                               52126
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN03B                              52127
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN04                               52128
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN04B                              52129
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN06                               52130
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN06B                              52131
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN07                               52132
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN07B                              52133
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN08                               52134
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN08B                              52135
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN09                               52136
#define IDGS_TPCREWSPEECHTUGEHS_HELMSMAN09B                              52137
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER01                                52138
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER02                                52139
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER03                                52140
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER05                                52141
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER06                                52142
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER06B                               52143
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER07                                52144
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER08                                52145
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER09                                52146
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER10                                52147
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER11                                52148
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER12                                52149
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER13                                52150
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER14                                52151
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER15                                52152
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER16                                52153
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER17                                52154
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER18                                52155
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER19                                52156
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER20                                52157
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER21                                52158
#define IDGS_TPCREWSPEECHTUGEHS_SPOTTER22                                52159
