// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER01                               51500
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER01B                              51501
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER02                               51502
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER02B                              51503
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER03                               51504
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER03B                              51505
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER04                               51506
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER05                               51507
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER06                               51508
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER06B                              51509
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER07                               51510
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER07B                              51511
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER08                               51512
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER08B                              51513
#define IDGS_TPCREWSPEECHOPGEHS_ENGINEER09                               51514
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER01                                 51515
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER02                                 51516
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER03                                 51517
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER04                                 51518
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER05                                 51519
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER06                                 51520
#define IDGS_TPCREWSPEECHOPGEHS_GUNNER06B                                51521
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN01                               51522
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN01B                              51523
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN02                               51524
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN02B                              51525
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN03                               51526
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN03B                              51527
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN04                               51528
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN04B                              51529
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN06                               51530
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN06B                              51531
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN07                               51532
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN07B                              51533
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN08                               51534
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN08B                              51535
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN09                               51536
#define IDGS_TPCREWSPEECHOPGEHS_HELMSMAN09B                              51537
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER01                                51538
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER02                                51539
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER03                                51540
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER05                                51541
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER06                                51542
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER06B                               51543
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER07                                51544
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER08                                51545
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER09                                51546
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER10                                51547
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER11                                51548
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER12                                51549
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER13                                51550
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER14                                51551
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER15                                51552
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER16                                51553
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER17                                51554
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER18                                51555
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER19                                51556
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER20                                51557
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER21                                51558
#define IDGS_TPCREWSPEECHOPGEHS_SPOTTER22                                51559
