// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN02B                              51000
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN03B                              51001
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN04                               51002
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN04B                              51003
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN05                               51004
#define IDGS_TPCREWSPEECHHMRFC_AICAPTAIN05B                              51005
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN01                                 51006
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN02                                 51007
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN03                                 51008
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN04                                 51009
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN05                                 51010
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN06                                 51011
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN07                                 51012
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN08                                 51013
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN09                                 51014
#define IDGS_TPCREWSPEECHHMRFC_CAPTAIN10                                 51015
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE01                               51016
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE01B                              51017
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE02                               51018
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE02B                              51019
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE03                               51020
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE04                               51021
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE04B                              51022
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE05                               51023
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE06                               51024
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE06B                              51025
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE07                               51026
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE08                               51027
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE09                               51028
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE11                               51029
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE12                               51030
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE12B                              51031
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE13                               51032
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE14                               51033
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE14B                              51034
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE15                               51035
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE15B                              51036
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE16                               51037
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE16B                              51038
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE18                               51039
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE19                               51040
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE20                               51041
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE20B                              51042
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE21                               51043
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE22                               51044
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE23                               51045
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE24                               51046
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE26                               51047
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE26B                              51048
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE27                               51049
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE27B                              51050
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE28                               51051
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE28B                              51052
#define IDGS_TPCREWSPEECHHMRFC_FIRSTMATE29                               51053
#define IDGS_TPCREWSPEECHHMRFC_RIGGER03                                  51054
#define IDGS_TPCREWSPEECHHMRFC_RIGGER03B                                 51055
#define IDGS_TPCREWSPEECHHMRFC_RIGGER04                                  51056
#define IDGS_TPCREWSPEECHHMRFC_RIGGER04B                                 51057
#define IDGS_TPCREWSPEECHHMRFC_RIGGER05                                  51058
#define IDGS_TPCREWSPEECHHMRFC_RIGGER06                                  51059
