// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWNAME_ALEXANDERGODFREY                                 48900
#define IDGS_TPCREWNAME_AMELIA                                           48901
#define IDGS_TPCREWNAME_ANTOINEBONBON                                    48902
#define IDGS_TPCREWNAME_ANTONIOMANCERAS                                  48903
#define IDGS_TPCREWNAME_ARSENKANNON                                      48904
#define IDGS_TPCREWNAME_BARIANLABRUTE                                    48905
#define IDGS_TPCREWNAME_BARNACLEBOB                                      48906
#define IDGS_TPCREWNAME_BENJAMINHARRINGTON                               48907
#define IDGS_TPCREWNAME_BLACKBART                                        48908
#define IDGS_TPCREWNAME_BLINDGERNIE                                      48909
#define IDGS_TPCREWNAME_BOBWATTS                                         48910
#define IDGS_TPCREWNAME_BRENNANDAMOURES                                  48911
#define IDGS_TPCREWNAME_CALICOJACK                                       48912
#define IDGS_TPCREWNAME_CAPTAINBARKINGMARK                               48913
#define IDGS_TPCREWNAME_CLAUDELEDIABLE                                   48914
#define IDGS_TPCREWNAME_CUTTHROATKELLY                                   48915
#define IDGS_TPCREWNAME_DOMINOELTORO                                     48916
#define IDGS_TPCREWNAME_DRDOPPLER                                        48917
#define IDGS_TPCREWNAME_EDTEACH                                          48918
#define IDGS_TPCREWNAME_ENRIQUEDELRIO                                    48919
#define IDGS_TPCREWNAME_FISHYPETE                                        48920
#define IDGS_TPCREWNAME_GALLSKIP                                         48921
#define IDGS_TPCREWNAME_GEARSTUMP                                        48922
#define IDGS_TPCREWNAME_GENTLEFRANK                                      48923
#define IDGS_TPCREWNAME_GERSPACHGLICK                                    48924
#define IDGS_TPCREWNAME_GIOHIGGS                                         48925
#define IDGS_TPCREWNAME_GOLDTOOTHJONES                                   48926
#define IDGS_TPCREWNAME_GORDONWRECKELL                                   48927
#define IDGS_TPCREWNAME_GRIG                                             48928
#define IDGS_TPCREWNAME_HANDS                                            48929
#define IDGS_TPCREWNAME_HORSESHOEJACK                                    48930
#define IDGS_TPCREWNAME_JACKTHINKER                                      48931
#define IDGS_TPCREWNAME_JAXXORTHEBOLD                                    48932
#define IDGS_TPCREWNAME_JEANLAFITTE                                      48933
#define IDGS_TPCREWNAME_JIMHAWKINS                                       48934
#define IDGS_TPCREWNAME_JJRACKMAN                                        48935
#define IDGS_TPCREWNAME_JOHNSILVER                                       48936
#define IDGS_TPCREWNAME_JOLLYROGUE                                       48937
#define IDGS_TPCREWNAME_JOSEDAMIGO                                       48938
#define IDGS_TPCREWNAME_JUANCASTEZ                                       48939
#define IDGS_TPCREWNAME_LEOBLUE                                          48940
#define IDGS_TPCREWNAME_LUCIENGUNNER                                     48941
#define IDGS_TPCREWNAME_LUCKYLANCE                                       48942
#define IDGS_TPCREWNAME_LUTHERVANSAL                                     48943
#define IDGS_TPCREWNAME_MADDOGMECRON                                     48944
#define IDGS_TPCREWNAME_MANUELCASSA                                      48945
#define IDGS_TPCREWNAME_MARCOSBOLITO                                     48946
#define IDGS_TPCREWNAME_MELTDOWN                                         48947
#define IDGS_TPCREWNAME_MICKEYMOUSE                                      48948
#define IDGS_TPCREWNAME_MISTERONYX                                       48949
#define IDGS_TPCREWNAME_MVR_HATCH                                        48950
#define IDGS_TPCREWNAME_MVR_KRAAL                                        48951
#define IDGS_TPCREWNAME_MVR_SCORN                                        48952
#define IDGS_TPCREWNAME_MVR_SCROOP                                       48953
#define IDGS_TPCREWNAME_MVR_SKRIP                                        48954
#define IDGS_TPCREWNAME_ONOS                                             48955
#define IDGS_TPCREWNAME_PACKLORA                                         48956
#define IDGS_TPCREWNAME_PEDRONUNEZ                                       48957
#define IDGS_TPCREWNAME_PETESTCLAUS                                      48958
#define IDGS_TPCREWNAME_PRC_ALKRET                                       48959
#define IDGS_TPCREWNAME_PRC_GORMUNSUN                                    48960
#define IDGS_TPCREWNAME_PRC_GRAGAS                                       48961
#define IDGS_TPCREWNAME_PRC_KENNSLU                                      48962
#define IDGS_TPCREWNAME_PRC_STOFFMUN                                     48963
#define IDGS_TPCREWNAME_PRC_STYRKIR                                      48964
#define IDGS_TPCREWNAME_PRC_TENGLAR                                      48965
#define IDGS_TPCREWNAME_RICARDOANDALES                                   48966
#define IDGS_TPCREWNAME_ROCKBRASILIANO                                   48967
#define IDGS_TPCREWNAME_SAMUELDKROOK                                     48968
#define IDGS_TPCREWNAME_SEAMUSSEADOG                                     48969
#define IDGS_TPCREWNAME_SERPICOLANCER                                    48970
#define IDGS_TPCREWNAME_SIMONDANSER                                      48971
#define IDGS_TPCREWNAME_SMITHLEVITE                                      48972
#define IDGS_TPCREWNAME_STEDBONNET                                       48973
#define IDGS_TPCREWNAME_TOMLUPIN                                         48974
#define IDGS_TPCREWNAME_TURNBUCKLE                                       48975
#define IDGS_TPCREWNAME_VELASCOVERRA                                     48976
#define IDGS_TPCREWNAME_WAXWHITTAKER                                     48977
#define IDGS_TPCREWNAME_WBT_XRL_O1                                       48978
#define IDGS_TPCREWNAME_WBT_XRL_O2                                       48979
#define IDGS_TPCREWNAME_WBT_XRL_O3                                       48980
#define IDGS_TPCREWNAME_WBT_XRL_O4                                       48981
#define IDGS_TPCREWNAME_WBT_XRL_O5                                       48982
#define IDGS_TPCREWNAME_WBT_XRL_O6                                       48983
#define IDGS_TPCREWNAME_WILFREDSUNRISE                                   48984
#define IDGS_TPCREWNAME_WILLKIDD                                         48985
#define IDGS_TPCREWNAME_WLR_FROMCHMM                                     48986
#define IDGS_TPCREWNAME_WLR_HONGRN                                       48987
#define IDGS_TPCREWNAME_WLR_KRUCHLU                                      48988
#define IDGS_TPCREWNAME_WLR_SLURGLU                                      48989
#define IDGS_TPCREWNAME_ZEROVALUE                                        48990
