// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWNAME02_ABRAHAMKEMPTON                                 49000
#define IDGS_TPCREWNAME02_ADAMFALTZ                                      49001
#define IDGS_TPCREWNAME02_ANDREWMCCULLEN                                 49002
#define IDGS_TPCREWNAME02_ARON                                           49003
#define IDGS_TPCREWNAME02_ARTHURLITTLE                                   49004
#define IDGS_TPCREWNAME02_AURORA                                         49005
#define IDGS_TPCREWNAME02_BEN0001                                        49006
#define IDGS_TPCREWNAME02_BEN0002                                        49007
#define IDGS_TPCREWNAME02_BEN0003                                        49008
#define IDGS_TPCREWNAME02_BEN0004                                        49009
#define IDGS_TPCREWNAME02_BEN0005                                        49010
#define IDGS_TPCREWNAME02_BOAS                                           49011
#define IDGS_TPCREWNAME02_BOLDHECKLAND                                   49012
#define IDGS_TPCREWNAME02_BRETINA                                        49013
#define IDGS_TPCREWNAME02_BRITANIA                                       49014
#define IDGS_TPCREWNAME02_BRUCEMCDERMITH                                 49015
#define IDGS_TPCREWNAME02_BUB0001                                        49016
#define IDGS_TPCREWNAME02_BUB0002                                        49017
#define IDGS_TPCREWNAME02_BUB0003                                        49018
#define IDGS_TPCREWNAME02_BUB0004                                        49019
#define IDGS_TPCREWNAME02_BUB0005                                        49020
#define IDGS_TPCREWNAME02_CHRISTOPHERSWINGTELL                           49021
#define IDGS_TPCREWNAME02_CORNELIUSKNOWLOT                               49022
#define IDGS_TPCREWNAME02_CREEZY                                         49023
#define IDGS_TPCREWNAME02_DAMIANCURLINGHTON                              49024
#define IDGS_TPCREWNAME02_DRAUPNIR                                       49025
#define IDGS_TPCREWNAME02_EDMONDBATES                                    49026
#define IDGS_TPCREWNAME02_EGGERT                                         49027
#define IDGS_TPCREWNAME02_ELIZABETH                                      49028
#define IDGS_TPCREWNAME02_EVAR                                           49029
#define IDGS_TPCREWNAME02_FRANCESMARY                                    49030
#define IDGS_TPCREWNAME02_FRANCISELLISON                                 49031
#define IDGS_TPCREWNAME02_FRANCISWALLACE                                 49032
#define IDGS_TPCREWNAME02_FREEZBU                                        49033
#define IDGS_TPCREWNAME02_GARRETSWINESBURG                               49034
#define IDGS_TPCREWNAME02_GEEZMOT                                        49035
#define IDGS_TPCREWNAME02_GEORGEVAUGHEN                                  49036
#define IDGS_TPCREWNAME02_GREETCH                                        49037
#define IDGS_TPCREWNAME02_HARALDUR                                       49038
#define IDGS_TPCREWNAME02_HENRYHEARTSTONE                                49039
#define IDGS_TPCREWNAME02_HIBERNIA                                       49040
#define IDGS_TPCREWNAME02_HUGHMANSFIELD                                  49041
#define IDGS_TPCREWNAME02_JAAZEE                                         49042
#define IDGS_TPCREWNAME02_JAMESALMS                                      49043
#define IDGS_TPCREWNAME02_JAMESNEWCOMB                                   49044
#define IDGS_TPCREWNAME02_JAMESNILBY                                     49045
#define IDGS_TPCREWNAME02_JEFFREYGOODWILL                                49046
#define IDGS_TPCREWNAME02_JENEREGARDE                                    49047
#define IDGS_TPCREWNAME02_JOHNMOODY                                      49048
#define IDGS_TPCREWNAME02_JOSEPHBANGS                                    49049
#define IDGS_TPCREWNAME02_KAROLINE                                       49050
#define IDGS_TPCREWNAME02_KENEYE                                         49051
#define IDGS_TPCREWNAME02_KLEEPTO                                        49052
#define IDGS_TPCREWNAME02_KOBLEIN                                        49053
#define IDGS_TPCREWNAME02_LARUS                                          49054
#define IDGS_TPCREWNAME02_LAURENCESTRONG                                 49055
#define IDGS_TPCREWNAME02_LEIFUR                                         49056
#define IDGS_TPCREWNAME02_LOLUK                                          49057
#define IDGS_TPCREWNAME02_MARIOKINSTON                                   49058
#define IDGS_TPCREWNAME02_MAYFLOWER                                      49059
#define IDGS_TPCREWNAME02_MEBLIND                                        49060
#define IDGS_TPCREWNAME02_MEELOT                                         49061
#define IDGS_TPCREWNAME02_MICHEALWATERS                                  49062
#define IDGS_TPCREWNAME02_MINERVA                                        49063
#define IDGS_TPCREWNAME02_MONOEIL                                        49064
#define IDGS_TPCREWNAME02_MORESDOLLIVER                                  49065
#define IDGS_TPCREWNAME02_MURDOCKMCFARLANE                               49066
#define IDGS_TPCREWNAME02_NAAZ                                           49067
#define IDGS_TPCREWNAME02_NATHANSTONE                                    49068
#define IDGS_TPCREWNAME02_NEILSONCROWELL                                 49069
#define IDGS_TPCREWNAME02_NOI                                            49070
#define IDGS_TPCREWNAME02_OTTAR                                          49071
#define IDGS_TPCREWNAME02_OWENREID                                       49072
#define IDGS_TPCREWNAME02_PASVUE                                         49073
#define IDGS_TPCREWNAME02_PATMCKELLY                                     49074
#define IDGS_TPCREWNAME02_PATRICKTHORNTON                                49075
#define IDGS_TPCREWNAME02_POCK-C                                         49076
#define IDGS_TPCREWNAME02_REYNIR                                         49077
#define IDGS_TPCREWNAME02_RICHARDLAMONT                                  49078
#define IDGS_TPCREWNAME02_ROBERTCHURCHILL                                49079
#define IDGS_TPCREWNAME02_SAMHUTCHKINS                                   49080
#define IDGS_TPCREWNAME02_SIGMAR                                         49081
#define IDGS_TPCREWNAME02_STEPHENSPARKES                                 49082
#define IDGS_TPCREWNAME02_THOMASBRINLEY                                  49083
#define IDGS_TPCREWNAME02_TOUVUT                                         49084
#define IDGS_TPCREWNAME02_TURNIK                                         49085
#define IDGS_TPCREWNAME02_WALTERLEWIS                                    49086
#define IDGS_TPCREWNAME02_WILLIAMYOUNG                                   49087
#define IDGS_TPCREWNAME02_ZEPHONEPARR                                    49088
