// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN02B                              50000
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN03B                              50001
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN04                               50002
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN04B                              50003
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN05                               50004
#define IDGS_TPCREWSPEECHCRRFC_AICAPTAIN05B                              50005
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN01                                 50006
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN02                                 50007
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN03                                 50008
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN04                                 50009
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN05                                 50010
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN06                                 50011
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN07                                 50012
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN08                                 50013
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN09                                 50014
#define IDGS_TPCREWSPEECHCRRFC_CAPTAIN10                                 50015
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE01                               50016
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE01B                              50017
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE02                               50018
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE02B                              50019
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE03                               50020
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE04                               50021
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE04B                              50022
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE05                               50023
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE06                               50024
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE06B                              50025
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE07                               50026
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE08                               50027
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE09                               50028
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE11                               50029
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE12                               50030
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE12B                              50031
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE13                               50032
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE14                               50033
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE14B                              50034
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE15                               50035
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE15B                              50036
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE16                               50037
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE16B                              50038
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE18                               50039
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE19                               50040
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE20                               50041
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE20B                              50042
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE21                               50043
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE22                               50044
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE23                               50045
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE24                               50046
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE26                               50047
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE26B                              50048
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE27                               50049
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE27B                              50050
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE28                               50051
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE28B                              50052
#define IDGS_TPCREWSPEECHCRRFC_FIRSTMATE29                               50053
#define IDGS_TPCREWSPEECHCRRFC_RIGGER03                                  50054
#define IDGS_TPCREWSPEECHCRRFC_RIGGER03B                                 50055
#define IDGS_TPCREWSPEECHCRRFC_RIGGER04                                  50056
#define IDGS_TPCREWSPEECHCRRFC_RIGGER04B                                 50057
#define IDGS_TPCREWSPEECHCRRFC_RIGGER05                                  50058
#define IDGS_TPCREWSPEECHCRRFC_RIGGER06                                  50059
