// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN02B                              49400
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN03B                              49401
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN04                               49402
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN04B                              49403
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN05                               49404
#define IDGS_TPCREWSPEECHAQRFC_AICAPTAIN05B                              49405
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN01                                 49406
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN02                                 49407
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN03                                 49408
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN04                                 49409
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN05                                 49410
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN06                                 49411
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN07                                 49412
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN08                                 49413
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN09                                 49414
#define IDGS_TPCREWSPEECHAQRFC_CAPTAIN10                                 49415
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE01                               49416
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE01B                              49417
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE02                               49418
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE02B                              49419
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE03                               49420
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE04                               49421
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE04B                              49422
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE05                               49423
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE06                               49424
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE06B                              49425
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE07                               49426
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE08                               49427
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE09                               49428
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE11                               49429
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE12                               49430
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE12B                              49431
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE13                               49432
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE14                               49433
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE14B                              49434
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE15                               49435
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE15B                              49436
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE16                               49437
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE16B                              49438
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE18                               49439
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE19                               49440
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE20                               49441
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE20B                              49442
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE21                               49443
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE22                               49444
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE23                               49445
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE24                               49446
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE26                               49447
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE26B                              49448
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE27                               49449
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE27B                              49450
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE28                               49451
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE28B                              49452
#define IDGS_TPCREWSPEECHAQRFC_FIRSTMATE29                               49453
#define IDGS_TPCREWSPEECHAQRFC_RIGGER03                                  49454
#define IDGS_TPCREWSPEECHAQRFC_RIGGER03B                                 49455
#define IDGS_TPCREWSPEECHAQRFC_RIGGER04                                  49456
#define IDGS_TPCREWSPEECHAQRFC_RIGGER04B                                 49457
#define IDGS_TPCREWSPEECHAQRFC_RIGGER05                                  49458
#define IDGS_TPCREWSPEECHAQRFC_RIGGER06                                  49459
