// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWNAME04_HUMF_NAVY_ANNABELANDREWS                       49200
#define IDGS_TPCREWNAME04_HUMF_NAVY_ELIZABETHBARTLETT                    49201
#define IDGS_TPCREWNAME04_HUMF_NAVY_OLIVIAFLAVERSHAM                     49202
#define IDGS_TPCREWNAME04_HUMF_NAVY_RACHELCRICKETT                       49203
#define IDGS_TPCREWNAME04_HUMF_PIRATE_AMYPEDERSON                        49204
#define IDGS_TPCREWNAME04_HUMF_PIRATE_ANNECORMAC                         49205
#define IDGS_TPCREWNAME04_HUMF_PIRATE_BLACKOAKGRACE                      49206
#define IDGS_TPCREWNAME04_HUMF_PIRATE_CUTTHROATLIZ                       49207
#define IDGS_TPCREWNAME04_HUMF_PIRATE_GERTIESTUBBS                       49208
#define IDGS_TPCREWNAME04_HUMF_PIRATE_LENOREKILLIGREW                    49209
#define IDGS_TPCREWNAME04_HUMF_PIRATE_MAGGIEJORDAN                       49210
#define IDGS_TPCREWNAME04_HUMF_PIRATE_MARYDEVON                          49211
#define IDGS_TPCREWNAME04_HUMF_PIRATE_PENNYWISEKELLY                     49212
#define IDGS_TPCREWNAME04_HUMF_PIRATE_SCATTERSHOTBETH                    49213
#define IDGS_TPCREWNAME04_HUMM_NAVY_LEEPEDERSON                          49214
#define IDGS_TPCREWNAME04_HUMM_PIRATE_FANCYBLAIR                         49215
#define IDGS_TPCREWNAME04_PROC_DAGUR                                     49216
#define IDGS_TPCREWNAME04_PROC_DETLOF                                    49217
#define IDGS_TPCREWNAME04_PROC_GUNNAR                                    49218
#define IDGS_TPCREWNAME04_PROC_IKKA                                      49219
#define IDGS_TPCREWNAME04_PROC_KETIL                                     49220
#define IDGS_TPCREWNAME04_PROC_KLAS                                      49221
#define IDGS_TPCREWNAME04_PROC_ORED                                      49222
#define IDGS_TPCREWNAME04_PROC_RAKEL                                     49223
#define IDGS_TPCREWNAME04_PROC_RIKARD                                    49224
#define IDGS_TPCREWNAME04_PROC_VIAR                                      49225
#define IDGS_TPCREWNAME04_PROC_VIG                                       49226
#define IDGS_TPCREWNAME04_ZIRR_PIRATE_TURNBUCKLE                         49227
