// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWNAME03_AQUA_BIGDENCH                                  49100
#define IDGS_TPCREWNAME03_AQUA_BORT                                      49101
#define IDGS_TPCREWNAME03_AQUA_CRUNALD                                   49102
#define IDGS_TPCREWNAME03_AQUA_GURKAN                                    49103
#define IDGS_TPCREWNAME03_AQUA_HORK                                      49104
#define IDGS_TPCREWNAME03_AQUA_HURNAY                                    49105
#define IDGS_TPCREWNAME03_AQUA_KRANG                                     49106
#define IDGS_TPCREWNAME03_AQUA_KRELL                                     49107
#define IDGS_TPCREWNAME03_AQUA_SNORK                                     49108
#define IDGS_TPCREWNAME03_AQUA_WUNSTON                                   49109
#define IDGS_TPCREWNAME03_ARC_ADMIRALNELSON                              49110
#define IDGS_TPCREWNAME03_ARC_JBIGBOOTE                                  49111
#define IDGS_TPCREWNAME03_ARC_JEMDALL                                    49112
#define IDGS_TPCREWNAME03_ARC_JGOMEZ                                     49113
#define IDGS_TPCREWNAME03_ARC_JGRANT                                     49114
#define IDGS_TPCREWNAME03_ARC_JOHNOCONNOR                                49115
#define IDGS_TPCREWNAME03_ARC_JPARKER                                    49116
#define IDGS_TPCREWNAME03_ARC_JSMALLBERRIES                              49117
#define IDGS_TPCREWNAME03_ARC_JWHORFIN                                   49118
#define IDGS_TPCREWNAME03_ARC_JYAYA                                      49119
#define IDGS_TPCREWNAME03_BEN0006                                        49120
#define IDGS_TPCREWNAME03_BEN0007                                        49121
#define IDGS_TPCREWNAME03_BEN0008                                        49122
#define IDGS_TPCREWNAME03_BEN0009                                        49123
#define IDGS_TPCREWNAME03_BEN0010                                        49124
#define IDGS_TPCREWNAME03_BEN0011                                        49125
#define IDGS_TPCREWNAME03_BEN0012                                        49126
#define IDGS_TPCREWNAME03_BEN0013                                        49127
#define IDGS_TPCREWNAME03_BEN0014                                        49128
#define IDGS_TPCREWNAME03_BEN0015                                        49129
#define IDGS_TPCREWNAME03_CND_CORNELIUSPITCH                             49130
#define IDGS_TPCREWNAME03_CND_ENGLEBERTFLANGE                            49131
#define IDGS_TPCREWNAME03_CND_PEMBLTONCHANNEL                            49132
#define IDGS_TPCREWNAME03_CND_PENFOLDTANGENT                             49133
#define IDGS_TPCREWNAME03_CND_REGINALDMEDIAN                             49134
#define IDGS_TPCREWNAME03_CND_RUTIGERQUAY                                49135
#define IDGS_TPCREWNAME03_CRAG_GALENA                                    49136
#define IDGS_TPCREWNAME03_CRAG_GRIT                                      49137
#define IDGS_TPCREWNAME03_CRAG_MORTAR                                    49138
#define IDGS_TPCREWNAME03_CRAG_QUARRY                                    49139
#define IDGS_TPCREWNAME03_CRAG_RUBBLE                                    49140
#define IDGS_TPCREWNAME03_CRAG_SLATE                                     49141
#define IDGS_TPCREWNAME03_CRAG_SPINEL                                    49142
#define IDGS_TPCREWNAME03_CRAG_TALC                                      49143
#define IDGS_TPCREWNAME03_DENS_CRUNK                                     49144
#define IDGS_TPCREWNAME03_DENS_HANDS                                     49145
#define IDGS_TPCREWNAME03_DENS_HIGHTOWER                                 49146
#define IDGS_TPCREWNAME03_DENS_HUGGY                                     49147
#define IDGS_TPCREWNAME03_DENS_KNUCKLES                                  49148
#define IDGS_TPCREWNAME03_DENS_MITTS                                     49149
#define IDGS_TPCREWNAME03_DENS_MUGSY                                     49150
#define IDGS_TPCREWNAME03_DENS_WALLY                                     49151
#define IDGS_TPCREWNAME03_GEIR                                           49152
#define IDGS_TPCREWNAME03_GENERALCREWAVERAGE                             49153
#define IDGS_TPCREWNAME03_GENERALCREWELITE                               49154
#define IDGS_TPCREWNAME03_GENERALCREWGREEN                               49155
#define IDGS_TPCREWNAME03_HACKVENS                                       49156
#define IDGS_TPCREWNAME03_HAKON                                          49157
#define IDGS_TPCREWNAME03_JENS                                           49158
#define IDGS_TPCREWNAME03_KALSIEN                                        49159
#define IDGS_TPCREWNAME03_KATCH                                          49160
#define IDGS_TPCREWNAME03_LORDHRALLSUN                                   49161
#define IDGS_TPCREWNAME03_MANT_KREET                                     49162
#define IDGS_TPCREWNAME03_MANT_KRIT                                      49163
#define IDGS_TPCREWNAME03_MANT_QUIB                                      49164
#define IDGS_TPCREWNAME03_MANT_SPAAT                                     49165
#define IDGS_TPCREWNAME03_MANT_TICH                                      49166
#define IDGS_TPCREWNAME03_MCRK_JIKILIKI                                  49167
#define IDGS_TPCREWNAME03_MCRK_KIKIMIKI                                  49168
#define IDGS_TPCREWNAME03_MCRK_RIKITIKI                                  49169
#define IDGS_TPCREWNAME03_MCRK_STIKIPIKI                                 49170
#define IDGS_TPCREWNAME03_MCRK_WIKIBLIKI                                 49171
#define IDGS_TPCREWNAME03_PROC_DONAR                                     49172
#define IDGS_TPCREWNAME03_PROC_JARKKO                                    49173
#define IDGS_TPCREWNAME03_PROC_TAGE                                      49174
#define IDGS_TPCREWNAME03_PROC_TERO                                      49175
#define IDGS_TPCREWNAME03_SELVALS                                        49176
#define IDGS_TPCREWNAME03_SKLOR                                          49177
#define IDGS_TPCREWNAME03_TUSK_SLURMGIR                                  49178
#define IDGS_TPCREWNAME03_TUSK_SPANGLR                                   49179
#define IDGS_TPCREWNAME03_TUSK_STINTS                                    49180
#define IDGS_TPCREWNAME03_TUSK_TRENGUP                                   49181
#define IDGS_TPCREWNAME03_TUSK_VINKMU                                    49182
#define IDGS_TPCREWNAME03_TUSK_WHINSTU                                   49183
#define IDGS_TPCREWNAME03_ZIRR_NAVY_CRIBZIBBINZ                          49184
#define IDGS_TPCREWNAME03_ZIRR_NAVY_ZALLSHOE_GRAPH                       49185
#define IDGS_TPCREWNAME03_ZIRR_NAVY_ZANEBEAKER                           49186
#define IDGS_TPCREWNAME03_ZIRR_NAVY_ZAPHODBOXTOPS                        49187
#define IDGS_TPCREWNAME03_ZIRR_NAVY_ZILASSRECIEPT                        49188
#define IDGS_TPCREWNAME03_ZIRR_NAVY_ZIRILIUSPATIO                        49189
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_SLOPBUCKETZUR                      49190
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_WHEELHOUSEZREELEN                  49191
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_WHEELZ                             49192
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_YARDARMZLICK                       49193
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZACKWOODPLANK                      49194
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZAPPOOPDECK                        49195
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZILCHTARP                          49196
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZIMNICKLES                         49197
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZORKNARHARDTACK                    49198
#define IDGS_TPCREWNAME03_ZIRR_PIRATE_ZULTONFOOTPEDALS                   49199
