// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN02B                              51400
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN03B                              51401
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN04                               51402
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN04B                              51403
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN05                               51404
#define IDGS_TPCREWSPEECHMNRFC_AICAPTAIN05B                              51405
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN01                                 51406
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN02                                 51407
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN03                                 51408
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN04                                 51409
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN05                                 51410
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN06                                 51411
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN07                                 51412
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN08                                 51413
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN09                                 51414
#define IDGS_TPCREWSPEECHMNRFC_CAPTAIN10                                 51415
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE01                               51416
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE01B                              51417
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE02                               51418
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE02B                              51419
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE03                               51420
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE04                               51421
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE04B                              51422
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE05                               51423
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE06                               51424
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE06B                              51425
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE07                               51426
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE08                               51427
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE09                               51428
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE11                               51429
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE12                               51430
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE12B                              51431
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE13                               51432
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE14                               51433
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE14B                              51434
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE15                               51435
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE15B                              51436
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE16                               51437
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE16B                              51438
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE18                               51439
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE19                               51440
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE20                               51441
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE20B                              51442
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE21                               51443
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE22                               51444
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE23                               51445
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE24                               51446
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE26                               51447
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE26B                              51448
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE27                               51449
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE27B                              51450
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE28                               51451
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE28B                              51452
#define IDGS_TPCREWSPEECHMNRFC_FIRSTMATE29                               51453
#define IDGS_TPCREWSPEECHMNRFC_RIGGER03                                  51454
#define IDGS_TPCREWSPEECHMNRFC_RIGGER03B                                 51455
#define IDGS_TPCREWSPEECHMNRFC_RIGGER04                                  51456
#define IDGS_TPCREWSPEECHMNRFC_RIGGER04B                                 51457
#define IDGS_TPCREWSPEECHMNRFC_RIGGER05                                  51458
#define IDGS_TPCREWSPEECHMNRFC_RIGGER06                                  51459
