// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN02B                              49800
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN03B                              49801
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN04                               49802
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN04B                              49803
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN05                               49804
#define IDGS_TPCREWSPEECHCARFC_AICAPTAIN05B                              49805
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN01                                 49806
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN02                                 49807
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN03                                 49808
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN04                                 49809
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN05                                 49810
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN06                                 49811
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN07                                 49812
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN08                                 49813
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN09                                 49814
#define IDGS_TPCREWSPEECHCARFC_CAPTAIN10                                 49815
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE01                               49816
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE01B                              49817
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE02                               49818
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE02B                              49819
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE03                               49820
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE04                               49821
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE04B                              49822
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE05                               49823
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE06                               49824
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE06B                              49825
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE07                               49826
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE08                               49827
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE09                               49828
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE11                               49829
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE12                               49830
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE12B                              49831
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE13                               49832
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE14                               49833
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE14B                              49834
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE15                               49835
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE15B                              49836
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE16                               49837
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE16B                              49838
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE18                               49839
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE19                               49840
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE20                               49841
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE20B                              49842
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE21                               49843
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE22                               49844
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE23                               49845
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE24                               49846
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE26                               49847
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE26B                              49848
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE27                               49849
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE27B                              49850
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE28                               49851
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE28B                              49852
#define IDGS_TPCREWSPEECHCARFC_FIRSTMATE29                               49853
#define IDGS_TPCREWSPEECHCARFC_RIGGER03                                  49854
#define IDGS_TPCREWSPEECHCARFC_RIGGER03B                                 49855
#define IDGS_TPCREWSPEECHCARFC_RIGGER04                                  49856
#define IDGS_TPCREWSPEECHCARFC_RIGGER04B                                 49857
#define IDGS_TPCREWSPEECHCARFC_RIGGER05                                  49858
#define IDGS_TPCREWSPEECHCARFC_RIGGER06                                  49859
