// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN02B                              52200
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN03B                              52201
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN04                               52202
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN04B                              52203
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN05                               52204
#define IDGS_TPCREWSPEECHTURFC_AICAPTAIN05B                              52205
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN01                                 52206
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN02                                 52207
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN03                                 52208
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN04                                 52209
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN05                                 52210
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN06                                 52211
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN07                                 52212
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN08                                 52213
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN09                                 52214
#define IDGS_TPCREWSPEECHTURFC_CAPTAIN10                                 52215
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE01                               52216
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE01B                              52217
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE02                               52218
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE02B                              52219
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE03                               52220
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE04                               52221
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE04B                              52222
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE05                               52223
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE06                               52224
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE06B                              52225
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE07                               52226
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE08                               52227
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE09                               52228
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE11                               52229
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE12                               52230
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE12B                              52231
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE13                               52232
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE14                               52233
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE14B                              52234
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE15                               52235
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE15B                              52236
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE16                               52237
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE16B                              52238
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE18                               52239
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE19                               52240
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE20                               52241
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE20B                              52242
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE21                               52243
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE22                               52244
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE23                               52245
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE24                               52246
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE26                               52247
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE26B                              52248
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE27                               52249
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE27B                              52250
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE28                               52251
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE28B                              52252
#define IDGS_TPCREWSPEECHTURFC_FIRSTMATE29                               52253
#define IDGS_TPCREWSPEECHTURFC_RIGGER03                                  52254
#define IDGS_TPCREWSPEECHTURFC_RIGGER03B                                 52255
#define IDGS_TPCREWSPEECHTURFC_RIGGER04                                  52256
#define IDGS_TPCREWSPEECHTURFC_RIGGER04B                                 52257
#define IDGS_TPCREWSPEECHTURFC_RIGGER05                                  52258
#define IDGS_TPCREWSPEECHTURFC_RIGGER06                                  52259
