// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER01                               50700
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER01B                              50701
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER02                               50702
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER02B                              50703
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER03                               50704
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER03B                              50705
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER04                               50706
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER05                               50707
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER06                               50708
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER06B                              50709
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER07                               50710
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER07B                              50711
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER08                               50712
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER08B                              50713
#define IDGS_TPCREWSPEECHHFGEHS_ENGINEER09                               50714
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER01                                 50715
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER02                                 50716
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER03                                 50717
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER04                                 50718
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER05                                 50719
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER06                                 50720
#define IDGS_TPCREWSPEECHHFGEHS_GUNNER06B                                50721
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN01                               50722
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN01B                              50723
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN02                               50724
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN02B                              50725
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN03                               50726
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN03B                              50727
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN04                               50728
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN04B                              50729
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN06                               50730
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN06B                              50731
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN07                               50732
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN07B                              50733
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN08                               50734
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN08B                              50735
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN09                               50736
#define IDGS_TPCREWSPEECHHFGEHS_HELMSMAN09B                              50737
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER01                                50738
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER02                                50739
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER03                                50740
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER05                                50741
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER06                                50742
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER06B                               50743
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER07                                50744
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER08                                50745
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER09                                50746
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER10                                50747
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER11                                50748
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER12                                50749
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER13                                50750
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER14                                50751
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER15                                50752
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER16                                50753
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER17                                50754
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER18                                50755
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER19                                50756
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER20                                50757
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER21                                50758
#define IDGS_TPCREWSPEECHHFGEHS_SPOTTER22                                50759
