// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER01                               49500
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER01B                              49501
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER02                               49502
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER02B                              49503
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER03                               49504
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER03B                              49505
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER04                               49506
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER05                               49507
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER06                               49508
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER06B                              49509
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER07                               49510
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER07B                              49511
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER08                               49512
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER08B                              49513
#define IDGS_TPCREWSPEECHARGEHS_ENGINEER09                               49514
#define IDGS_TPCREWSPEECHARGEHS_GUNNER01                                 49515
#define IDGS_TPCREWSPEECHARGEHS_GUNNER02                                 49516
#define IDGS_TPCREWSPEECHARGEHS_GUNNER03                                 49517
#define IDGS_TPCREWSPEECHARGEHS_GUNNER04                                 49518
#define IDGS_TPCREWSPEECHARGEHS_GUNNER05                                 49519
#define IDGS_TPCREWSPEECHARGEHS_GUNNER06                                 49520
#define IDGS_TPCREWSPEECHARGEHS_GUNNER06B                                49521
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN01                               49522
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN01B                              49523
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN02                               49524
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN02B                              49525
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN03                               49526
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN03B                              49527
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN04                               49528
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN04B                              49529
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN06                               49530
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN06B                              49531
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN07                               49532
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN07B                              49533
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN08                               49534
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN08B                              49535
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN09                               49536
#define IDGS_TPCREWSPEECHARGEHS_HELMSMAN09B                              49537
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER01                                49538
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER02                                49539
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER03                                49540
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER05                                49541
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER06                                49542
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER06B                               49543
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER07                                49544
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER08                                49545
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER09                                49546
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER10                                49547
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER11                                49548
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER12                                49549
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER13                                49550
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER14                                49551
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER15                                49552
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER16                                49553
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER17                                49554
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER18                                49555
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER19                                49556
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER20                                49557
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER21                                49558
#define IDGS_TPCREWSPEECHARGEHS_SPOTTER22                                49559
