// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER01                               51300
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER01B                              51301
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER02                               51302
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER02B                              51303
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER03                               51304
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER03B                              51305
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER04                               51306
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER05                               51307
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER06                               51308
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER06B                              51309
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER07                               51310
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER07B                              51311
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER08                               51312
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER08B                              51313
#define IDGS_TPCREWSPEECHMNGEHS_ENGINEER09                               51314
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER01                                 51315
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER02                                 51316
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER03                                 51317
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER04                                 51318
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER05                                 51319
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER06                                 51320
#define IDGS_TPCREWSPEECHMNGEHS_GUNNER06B                                51321
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN01                               51322
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN01B                              51323
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN02                               51324
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN02B                              51325
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN03                               51326
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN03B                              51327
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN04                               51328
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN04B                              51329
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN06                               51330
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN06B                              51331
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN07                               51332
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN07B                              51333
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN08                               51334
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN08B                              51335
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN09                               51336
#define IDGS_TPCREWSPEECHMNGEHS_HELMSMAN09B                              51337
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER01                                51338
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER02                                51339
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER03                                51340
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER05                                51341
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER06                                51342
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER06B                               51343
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER07                                51344
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER08                                51345
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER09                                51346
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER10                                51347
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER11                                51348
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER12                                51349
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER13                                51350
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER14                                51351
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER15                                51352
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER16                                51353
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER17                                51354
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER18                                51355
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER19                                51356
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER20                                51357
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER21                                51358
#define IDGS_TPCREWSPEECHMNGEHS_SPOTTER22                                51359
