// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN02B                              49600
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN03B                              49601
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN04                               49602
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN04B                              49603
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN05                               49604
#define IDGS_TPCREWSPEECHARRFC_AICAPTAIN05B                              49605
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN01                                 49606
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN02                                 49607
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN03                                 49608
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN04                                 49609
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN05                                 49610
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN06                                 49611
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN07                                 49612
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN08                                 49613
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN09                                 49614
#define IDGS_TPCREWSPEECHARRFC_CAPTAIN10                                 49615
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE01                               49616
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE01B                              49617
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE02                               49618
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE02B                              49619
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE03                               49620
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE04                               49621
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE04B                              49622
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE05                               49623
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE06                               49624
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE06B                              49625
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE07                               49626
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE08                               49627
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE09                               49628
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE11                               49629
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE12                               49630
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE12B                              49631
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE13                               49632
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE14                               49633
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE14B                              49634
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE15                               49635
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE15B                              49636
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE16                               49637
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE16B                              49638
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE18                               49639
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE19                               49640
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE20                               49641
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE20B                              49642
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE21                               49643
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE22                               49644
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE23                               49645
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE24                               49646
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE26                               49647
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE26B                              49648
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE27                               49649
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE27B                              49650
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE28                               49651
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE28B                              49652
#define IDGS_TPCREWSPEECHARRFC_FIRSTMATE29                               49653
#define IDGS_TPCREWSPEECHARRFC_RIGGER03                                  49654
#define IDGS_TPCREWSPEECHARRFC_RIGGER03B                                 49655
#define IDGS_TPCREWSPEECHARRFC_RIGGER04                                  49656
#define IDGS_TPCREWSPEECHARRFC_RIGGER04B                                 49657
#define IDGS_TPCREWSPEECHARRFC_RIGGER05                                  49658
#define IDGS_TPCREWSPEECHARRFC_RIGGER06                                  49659
