// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER01                               51100
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER01B                              51101
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER02                               51102
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER02B                              51103
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER03                               51104
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER03B                              51105
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER04                               51106
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER05                               51107
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER06                               51108
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER06B                              51109
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER07                               51110
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER07B                              51111
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER08                               51112
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER08B                              51113
#define IDGS_TPCREWSPEECHMCGEHS_ENGINEER09                               51114
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER01                                 51115
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER02                                 51116
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER03                                 51117
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER04                                 51118
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER05                                 51119
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER06                                 51120
#define IDGS_TPCREWSPEECHMCGEHS_GUNNER06B                                51121
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN01                               51122
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN01B                              51123
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN02                               51124
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN02B                              51125
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN03                               51126
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN03B                              51127
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN04                               51128
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN04B                              51129
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN06                               51130
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN06B                              51131
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN07                               51132
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN07B                              51133
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN08                               51134
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN08B                              51135
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN09                               51136
#define IDGS_TPCREWSPEECHMCGEHS_HELMSMAN09B                              51137
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER01                                51138
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER02                                51139
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER03                                51140
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER05                                51141
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER06                                51142
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER06B                               51143
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER07                                51144
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER08                                51145
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER09                                51146
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER10                                51147
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER11                                51148
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER12                                51149
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER13                                51150
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER14                                51151
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER15                                51152
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER16                                51153
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER17                                51154
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER18                                51155
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER19                                51156
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER20                                51157
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER21                                51158
#define IDGS_TPCREWSPEECHMCGEHS_SPOTTER22                                51159
