// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER01                               51900
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER01B                              51901
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER02                               51902
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER02B                              51903
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER03                               51904
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER03B                              51905
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER04                               51906
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER05                               51907
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER06                               51908
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER06B                              51909
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER07                               51910
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER07B                              51911
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER08                               51912
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER08B                              51913
#define IDGS_TPCREWSPEECHROGEHS_ENGINEER09                               51914
#define IDGS_TPCREWSPEECHROGEHS_GUNNER01                                 51915
#define IDGS_TPCREWSPEECHROGEHS_GUNNER02                                 51916
#define IDGS_TPCREWSPEECHROGEHS_GUNNER03                                 51917
#define IDGS_TPCREWSPEECHROGEHS_GUNNER04                                 51918
#define IDGS_TPCREWSPEECHROGEHS_GUNNER05                                 51919
#define IDGS_TPCREWSPEECHROGEHS_GUNNER06                                 51920
#define IDGS_TPCREWSPEECHROGEHS_GUNNER06B                                51921
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN01                               51922
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN01B                              51923
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN02                               51924
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN02B                              51925
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN03                               51926
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN03B                              51927
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN04                               51928
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN04B                              51929
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN06                               51930
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN06B                              51931
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN07                               51932
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN07B                              51933
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN08                               51934
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN08B                              51935
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN09                               51936
#define IDGS_TPCREWSPEECHROGEHS_HELMSMAN09B                              51937
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER01                                51938
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER02                                51939
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER03                                51940
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER05                                51941
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER06                                51942
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER06B                               51943
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER07                                51944
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER08                                51945
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER09                                51946
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER10                                51947
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER11                                51948
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER12                                51949
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER13                                51950
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER14                                51951
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER15                                51952
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER16                                51953
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER17                                51954
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER18                                51955
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER19                                51956
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER20                                51957
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER21                                51958
#define IDGS_TPCREWSPEECHROGEHS_SPOTTER22                                51959
