// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN02B                              51200
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN03B                              51201
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN04                               51202
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN04B                              51203
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN05                               51204
#define IDGS_TPCREWSPEECHMCRFC_AICAPTAIN05B                              51205
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN01                                 51206
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN02                                 51207
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN03                                 51208
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN04                                 51209
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN05                                 51210
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN06                                 51211
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN07                                 51212
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN08                                 51213
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN09                                 51214
#define IDGS_TPCREWSPEECHMCRFC_CAPTAIN10                                 51215
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE01                               51216
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE01B                              51217
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE02                               51218
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE02B                              51219
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE03                               51220
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE04                               51221
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE04B                              51222
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE05                               51223
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE06                               51224
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE06B                              51225
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE07                               51226
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE08                               51227
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE09                               51228
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE11                               51229
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE12                               51230
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE12B                              51231
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE13                               51232
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE14                               51233
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE14B                              51234
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE15                               51235
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE15B                              51236
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE16                               51237
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE16B                              51238
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE18                               51239
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE19                               51240
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE20                               51241
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE20B                              51242
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE21                               51243
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE22                               51244
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE23                               51245
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE24                               51246
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE26                               51247
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE26B                              51248
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE27                               51249
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE27B                              51250
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE28                               51251
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE28B                              51252
#define IDGS_TPCREWSPEECHMCRFC_FIRSTMATE29                               51253
#define IDGS_TPCREWSPEECHMCRFC_RIGGER03                                  51254
#define IDGS_TPCREWSPEECHMCRFC_RIGGER03B                                 51255
#define IDGS_TPCREWSPEECHMCRFC_RIGGER04                                  51256
#define IDGS_TPCREWSPEECHMCRFC_RIGGER04B                                 51257
#define IDGS_TPCREWSPEECHMCRFC_RIGGER05                                  51258
#define IDGS_TPCREWSPEECHMCRFC_RIGGER06                                  51259
