// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER01                               49300
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER01B                              49301
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER02                               49302
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER02B                              49303
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER03                               49304
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER03B                              49305
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER04                               49306
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER05                               49307
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER06                               49308
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER06B                              49309
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER07                               49310
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER07B                              49311
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER08                               49312
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER08B                              49313
#define IDGS_TPCREWSPEECHAQGEHS_ENGINEER09                               49314
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER01                                 49315
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER02                                 49316
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER03                                 49317
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER04                                 49318
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER05                                 49319
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER06                                 49320
#define IDGS_TPCREWSPEECHAQGEHS_GUNNER06B                                49321
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN01                               49322
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN01B                              49323
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN02                               49324
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN02B                              49325
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN03                               49326
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN03B                              49327
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN04                               49328
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN04B                              49329
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN06                               49330
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN06B                              49331
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN07                               49332
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN07B                              49333
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN08                               49334
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN08B                              49335
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN09                               49336
#define IDGS_TPCREWSPEECHAQGEHS_HELMSMAN09B                              49337
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER01                                49338
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER02                                49339
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER03                                49340
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER05                                49341
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER06                                49342
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER06B                               49343
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER07                                49344
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER08                                49345
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER09                                49346
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER10                                49347
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER11                                49348
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER12                                49349
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER13                                49350
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER14                                49351
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER15                                49352
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER16                                49353
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER17                                49354
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER18                                49355
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER19                                49356
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER20                                49357
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER21                                49358
#define IDGS_TPCREWSPEECHAQGEHS_SPOTTER22                                49359
