// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER01                               50500
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER01B                              50501
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER02                               50502
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER02B                              50503
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER03                               50504
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER03B                              50505
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER04                               50506
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER05                               50507
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER06                               50508
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER06B                              50509
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER07                               50510
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER07B                              50511
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER08                               50512
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER08B                              50513
#define IDGS_TPCREWSPEECHGEGEHS_ENGINEER09                               50514
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER01                                 50515
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER02                                 50516
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER03                                 50517
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER04                                 50518
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER05                                 50519
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER06                                 50520
#define IDGS_TPCREWSPEECHGEGEHS_GUNNER06B                                50521
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN01                               50522
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN01B                              50523
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN02                               50524
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN02B                              50525
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN03                               50526
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN03B                              50527
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN04                               50528
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN04B                              50529
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN06                               50530
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN06B                              50531
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN07                               50532
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN07B                              50533
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN08                               50534
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN08B                              50535
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN09                               50536
#define IDGS_TPCREWSPEECHGEGEHS_HELMSMAN09B                              50537
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER01                                50538
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER02                                50539
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER03                                50540
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER05                                50541
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER06                                50542
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER06B                               50543
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER07                                50544
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER08                                50545
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER09                                50546
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER10                                50547
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER11                                50548
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER12                                50549
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER13                                50550
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER14                                50551
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER15                                50552
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER16                                50553
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER17                                50554
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER18                                50555
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER19                                50556
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER20                                50557
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER21                                50558
#define IDGS_TPCREWSPEECHGEGEHS_SPOTTER22                                50559
