// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN02B                              50800
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN03B                              50801
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN04                               50802
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN04B                              50803
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN05                               50804
#define IDGS_TPCREWSPEECHHFRFC_AICAPTAIN05B                              50805
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN01                                 50806
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN02                                 50807
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN03                                 50808
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN04                                 50809
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN05                                 50810
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN06                                 50811
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN07                                 50812
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN08                                 50813
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN09                                 50814
#define IDGS_TPCREWSPEECHHFRFC_CAPTAIN10                                 50815
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE01                               50816
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE01B                              50817
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE02                               50818
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE02B                              50819
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE03                               50820
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE04                               50821
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE04B                              50822
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE05                               50823
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE06                               50824
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE06B                              50825
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE07                               50826
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE08                               50827
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE09                               50828
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE11                               50829
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE12                               50830
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE12B                              50831
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE13                               50832
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE14                               50833
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE14B                              50834
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE15                               50835
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE15B                              50836
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE16                               50837
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE16B                              50838
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE18                               50839
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE19                               50840
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE20                               50841
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE20B                              50842
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE21                               50843
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE22                               50844
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE23                               50845
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE24                               50846
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE26                               50847
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE26B                              50848
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE27                               50849
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE27B                              50850
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE28                               50851
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE28B                              50852
#define IDGS_TPCREWSPEECHHFRFC_FIRSTMATE29                               50853
#define IDGS_TPCREWSPEECHHFRFC_RIGGER03                                  50854
#define IDGS_TPCREWSPEECHHFRFC_RIGGER03B                                 50855
#define IDGS_TPCREWSPEECHHFRFC_RIGGER04                                  50856
#define IDGS_TPCREWSPEECHHFRFC_RIGGER04B                                 50857
#define IDGS_TPCREWSPEECHHFRFC_RIGGER05                                  50858
#define IDGS_TPCREWSPEECHHFRFC_RIGGER06                                  50859
