// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER01                               52300
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER01B                              52301
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER02                               52302
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER02B                              52303
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER03                               52304
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER03B                              52305
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER04                               52306
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER05                               52307
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER06                               52308
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER06B                              52309
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER07                               52310
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER07B                              52311
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER08                               52312
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER08B                              52313
#define IDGS_TPCREWSPEECHZIGEHS_ENGINEER09                               52314
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER01                                 52315
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER02                                 52316
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER03                                 52317
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER04                                 52318
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER05                                 52319
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER06                                 52320
#define IDGS_TPCREWSPEECHZIGEHS_GUNNER06B                                52321
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN01                               52322
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN01B                              52323
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN02                               52324
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN02B                              52325
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN03                               52326
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN03B                              52327
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN04                               52328
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN04B                              52329
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN06                               52330
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN06B                              52331
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN07                               52332
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN07B                              52333
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN08                               52334
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN08B                              52335
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN09                               52336
#define IDGS_TPCREWSPEECHZIGEHS_HELMSMAN09B                              52337
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER01                                52338
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER02                                52339
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER03                                52340
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER05                                52341
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER06                                52342
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER06B                               52343
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER07                                52344
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER08                                52345
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER09                                52346
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER10                                52347
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER11                                52348
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER12                                52349
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER13                                52350
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER14                                52351
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER15                                52352
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER16                                52353
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER17                                52354
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER18                                52355
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER19                                52356
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER20                                52357
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER21                                52358
#define IDGS_TPCREWSPEECHZIGEHS_SPOTTER22                                52359
