// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN02B                              51600
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN03B                              51601
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN04                               51602
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN04B                              51603
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN05                               51604
#define IDGS_TPCREWSPEECHOPRFC_AICAPTAIN05B                              51605
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN01                                 51606
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN02                                 51607
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN03                                 51608
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN04                                 51609
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN05                                 51610
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN06                                 51611
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN07                                 51612
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN08                                 51613
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN09                                 51614
#define IDGS_TPCREWSPEECHOPRFC_CAPTAIN10                                 51615
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE01                               51616
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE01B                              51617
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE02                               51618
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE02B                              51619
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE03                               51620
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE04                               51621
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE04B                              51622
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE05                               51623
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE06                               51624
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE06B                              51625
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE07                               51626
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE08                               51627
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE09                               51628
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE11                               51629
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE12                               51630
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE12B                              51631
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE13                               51632
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE14                               51633
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE14B                              51634
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE15                               51635
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE15B                              51636
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE16                               51637
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE16B                              51638
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE18                               51639
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE19                               51640
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE20                               51641
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE20B                              51642
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE21                               51643
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE22                               51644
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE23                               51645
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE24                               51646
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE26                               51647
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE26B                              51648
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE27                               51649
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE27B                              51650
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE28                               51651
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE28B                              51652
#define IDGS_TPCREWSPEECHOPRFC_FIRSTMATE29                               51653
#define IDGS_TPCREWSPEECHOPRFC_RIGGER03                                  51654
#define IDGS_TPCREWSPEECHOPRFC_RIGGER03B                                 51655
#define IDGS_TPCREWSPEECHOPRFC_RIGGER04                                  51656
#define IDGS_TPCREWSPEECHOPRFC_RIGGER04B                                 51657
#define IDGS_TPCREWSPEECHOPRFC_RIGGER05                                  51658
#define IDGS_TPCREWSPEECHOPRFC_RIGGER06                                  51659
