// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN02B                              50400
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN03B                              50401
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN04                               50402
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN04B                              50403
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN05                               50404
#define IDGS_TPCREWSPEECHFERFC_AICAPTAIN05B                              50405
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN01                                 50406
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN02                                 50407
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN03                                 50408
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN04                                 50409
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN05                                 50410
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN06                                 50411
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN07                                 50412
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN08                                 50413
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN09                                 50414
#define IDGS_TPCREWSPEECHFERFC_CAPTAIN10                                 50415
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE01                               50416
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE01B                              50417
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE02                               50418
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE02B                              50419
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE03                               50420
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE04                               50421
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE04B                              50422
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE05                               50423
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE06                               50424
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE06B                              50425
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE07                               50426
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE08                               50427
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE09                               50428
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE11                               50429
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE12                               50430
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE12B                              50431
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE13                               50432
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE14                               50433
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE14B                              50434
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE15                               50435
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE15B                              50436
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE16                               50437
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE16B                              50438
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE18                               50439
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE19                               50440
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE20                               50441
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE20B                              50442
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE21                               50443
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE22                               50444
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE23                               50445
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE24                               50446
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE26                               50447
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE26B                              50448
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE27                               50449
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE27B                              50450
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE28                               50451
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE28B                              50452
#define IDGS_TPCREWSPEECHFERFC_FIRSTMATE29                               50453
#define IDGS_TPCREWSPEECHFERFC_RIGGER03                                  50454
#define IDGS_TPCREWSPEECHFERFC_RIGGER03B                                 50455
#define IDGS_TPCREWSPEECHFERFC_RIGGER04                                  50456
#define IDGS_TPCREWSPEECHFERFC_RIGGER04B                                 50457
#define IDGS_TPCREWSPEECHFERFC_RIGGER05                                  50458
#define IDGS_TPCREWSPEECHFERFC_RIGGER06                                  50459
