// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN02B                              50200
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN03B                              50201
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN04                               50202
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN04B                              50203
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN05                               50204
#define IDGS_TPCREWSPEECHDERFC_AICAPTAIN05B                              50205
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN01                                 50206
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN02                                 50207
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN03                                 50208
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN04                                 50209
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN05                                 50210
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN06                                 50211
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN07                                 50212
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN08                                 50213
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN09                                 50214
#define IDGS_TPCREWSPEECHDERFC_CAPTAIN10                                 50215
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE01                               50216
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE01B                              50217
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE02                               50218
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE02B                              50219
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE03                               50220
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE04                               50221
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE04B                              50222
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE05                               50223
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE06                               50224
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE06B                              50225
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE07                               50226
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE08                               50227
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE09                               50228
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE11                               50229
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE12                               50230
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE12B                              50231
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE13                               50232
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE14                               50233
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE14B                              50234
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE15                               50235
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE15B                              50236
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE16                               50237
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE16B                              50238
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE18                               50239
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE19                               50240
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE20                               50241
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE20B                              50242
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE21                               50243
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE22                               50244
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE23                               50245
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE24                               50246
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE26                               50247
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE26B                              50248
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE27                               50249
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE27B                              50250
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE28                               50251
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE28B                              50252
#define IDGS_TPCREWSPEECHDERFC_FIRSTMATE29                               50253
#define IDGS_TPCREWSPEECHDERFC_RIGGER03                                  50254
#define IDGS_TPCREWSPEECHDERFC_RIGGER03B                                 50255
#define IDGS_TPCREWSPEECHDERFC_RIGGER04                                  50256
#define IDGS_TPCREWSPEECHDERFC_RIGGER04B                                 50257
#define IDGS_TPCREWSPEECHDERFC_RIGGER05                                  50258
#define IDGS_TPCREWSPEECHDERFC_RIGGER06                                  50259
