// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER01                               49900
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER01B                              49901
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER02                               49902
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER02B                              49903
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER03                               49904
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER03B                              49905
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER04                               49906
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER05                               49907
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER06                               49908
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER06B                              49909
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER07                               49910
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER07B                              49911
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER08                               49912
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER08B                              49913
#define IDGS_TPCREWSPEECHCRGEHS_ENGINEER09                               49914
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER01                                 49915
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER02                                 49916
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER03                                 49917
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER04                                 49918
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER05                                 49919
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER06                                 49920
#define IDGS_TPCREWSPEECHCRGEHS_GUNNER06B                                49921
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN01                               49922
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN01B                              49923
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN02                               49924
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN02B                              49925
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN03                               49926
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN03B                              49927
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN04                               49928
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN04B                              49929
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN06                               49930
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN06B                              49931
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN07                               49932
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN07B                              49933
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN08                               49934
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN08B                              49935
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN09                               49936
#define IDGS_TPCREWSPEECHCRGEHS_HELMSMAN09B                              49937
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER01                                49938
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER02                                49939
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER03                                49940
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER05                                49941
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER06                                49942
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER06B                               49943
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER07                                49944
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER08                                49945
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER09                                49946
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER10                                49947
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER11                                49948
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER12                                49949
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER13                                49950
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER14                                49951
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER15                                49952
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER16                                49953
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER17                                49954
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER18                                49955
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER19                                49956
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER20                                49957
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER21                                49958
#define IDGS_TPCREWSPEECHCRGEHS_SPOTTER22                                49959
