// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN02B                              50600
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN03B                              50601
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN04                               50602
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN04B                              50603
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN05                               50604
#define IDGS_TPCREWSPEECHGERFC_AICAPTAIN05B                              50605
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN01                                 50606
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN02                                 50607
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN03                                 50608
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN04                                 50609
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN05                                 50610
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN06                                 50611
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN07                                 50612
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN08                                 50613
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN09                                 50614
#define IDGS_TPCREWSPEECHGERFC_CAPTAIN10                                 50615
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE01                               50616
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE01B                              50617
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE02                               50618
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE02B                              50619
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE03                               50620
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE04                               50621
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE04B                              50622
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE05                               50623
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE06                               50624
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE06B                              50625
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE07                               50626
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE08                               50627
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE09                               50628
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE11                               50629
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE12                               50630
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE12B                              50631
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE13                               50632
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE14                               50633
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE14B                              50634
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE15                               50635
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE15B                              50636
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE16                               50637
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE16B                              50638
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE18                               50639
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE19                               50640
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE20                               50641
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE20B                              50642
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE21                               50643
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE22                               50644
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE23                               50645
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE24                               50646
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE26                               50647
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE26B                              50648
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE27                               50649
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE27B                              50650
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE28                               50651
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE28B                              50652
#define IDGS_TPCREWSPEECHGERFC_FIRSTMATE29                               50653
#define IDGS_TPCREWSPEECHGERFC_RIGGER03                                  50654
#define IDGS_TPCREWSPEECHGERFC_RIGGER03B                                 50655
#define IDGS_TPCREWSPEECHGERFC_RIGGER04                                  50656
#define IDGS_TPCREWSPEECHGERFC_RIGGER04B                                 50657
#define IDGS_TPCREWSPEECHGERFC_RIGGER05                                  50658
#define IDGS_TPCREWSPEECHGERFC_RIGGER06                                  50659
