// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER01                               50300
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER01B                              50301
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER02                               50302
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER02B                              50303
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER03                               50304
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER03B                              50305
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER04                               50306
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER05                               50307
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER06                               50308
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER06B                              50309
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER07                               50310
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER07B                              50311
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER08                               50312
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER08B                              50313
#define IDGS_TPCREWSPEECHFEGEHS_ENGINEER09                               50314
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER01                                 50315
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER02                                 50316
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER03                                 50317
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER04                                 50318
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER05                                 50319
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER06                                 50320
#define IDGS_TPCREWSPEECHFEGEHS_GUNNER06B                                50321
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN01                               50322
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN01B                              50323
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN02                               50324
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN02B                              50325
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN03                               50326
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN03B                              50327
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN04                               50328
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN04B                              50329
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN06                               50330
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN06B                              50331
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN07                               50332
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN07B                              50333
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN08                               50334
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN08B                              50335
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN09                               50336
#define IDGS_TPCREWSPEECHFEGEHS_HELMSMAN09B                              50337
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER01                                50338
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER02                                50339
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER03                                50340
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER05                                50341
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER06                                50342
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER06B                               50343
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER07                                50344
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER08                                50345
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER09                                50346
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER10                                50347
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER11                                50348
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER12                                50349
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER13                                50350
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER14                                50351
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER15                                50352
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER16                                50353
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER17                                50354
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER18                                50355
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER19                                50356
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER20                                50357
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER21                                50358
#define IDGS_TPCREWSPEECHFEGEHS_SPOTTER22                                50359
