// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER01                               51700
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER01B                              51701
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER02                               51702
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER02B                              51703
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER03                               51704
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER03B                              51705
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER04                               51706
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER05                               51707
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER06                               51708
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER06B                              51709
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER07                               51710
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER07B                              51711
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER08                               51712
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER08B                              51713
#define IDGS_TPCREWSPEECHPRGEHS_ENGINEER09                               51714
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER01                                 51715
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER02                                 51716
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER03                                 51717
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER04                                 51718
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER05                                 51719
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER06                                 51720
#define IDGS_TPCREWSPEECHPRGEHS_GUNNER06B                                51721
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN01                               51722
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN01B                              51723
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN02                               51724
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN02B                              51725
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN03                               51726
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN03B                              51727
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN04                               51728
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN04B                              51729
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN06                               51730
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN06B                              51731
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN07                               51732
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN07B                              51733
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN08                               51734
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN08B                              51735
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN09                               51736
#define IDGS_TPCREWSPEECHPRGEHS_HELMSMAN09B                              51737
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER01                                51738
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER02                                51739
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER03                                51740
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER05                                51741
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER06                                51742
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER06B                               51743
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER07                                51744
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER08                                51745
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER09                                51746
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER10                                51747
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER11                                51748
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER12                                51749
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER13                                51750
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER14                                51751
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER15                                51752
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER16                                51753
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER17                                51754
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER18                                51755
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER19                                51756
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER20                                51757
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER21                                51758
#define IDGS_TPCREWSPEECHPRGEHS_SPOTTER22                                51759
