// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER01                               49700
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER01B                              49701
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER02                               49702
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER02B                              49703
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER03                               49704
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER03B                              49705
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER04                               49706
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER05                               49707
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER06                               49708
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER06B                              49709
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER07                               49710
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER07B                              49711
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER08                               49712
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER08B                              49713
#define IDGS_TPCREWSPEECHCAGEHS_ENGINEER09                               49714
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER01                                 49715
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER02                                 49716
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER03                                 49717
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER04                                 49718
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER05                                 49719
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER06                                 49720
#define IDGS_TPCREWSPEECHCAGEHS_GUNNER06B                                49721
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN01                               49722
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN01B                              49723
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN02                               49724
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN02B                              49725
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN03                               49726
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN03B                              49727
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN04                               49728
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN04B                              49729
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN06                               49730
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN06B                              49731
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN07                               49732
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN07B                              49733
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN08                               49734
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN08B                              49735
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN09                               49736
#define IDGS_TPCREWSPEECHCAGEHS_HELMSMAN09B                              49737
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER01                                49738
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER02                                49739
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER03                                49740
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER05                                49741
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER06                                49742
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER06B                               49743
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER07                                49744
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER08                                49745
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER09                                49746
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER10                                49747
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER11                                49748
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER12                                49749
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER13                                49750
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER14                                49751
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER15                                49752
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER16                                49753
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER17                                49754
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER18                                49755
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER19                                49756
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER20                                49757
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER21                                49758
#define IDGS_TPCREWSPEECHCAGEHS_SPOTTER22                                49759
