// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN02B                              52400
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN03B                              52401
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN04                               52402
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN04B                              52403
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN05                               52404
#define IDGS_TPCREWSPEECHZIRFC_AICAPTAIN05B                              52405
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN01                                 52406
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN02                                 52407
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN03                                 52408
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN04                                 52409
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN05                                 52410
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN06                                 52411
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN07                                 52412
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN08                                 52413
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN09                                 52414
#define IDGS_TPCREWSPEECHZIRFC_CAPTAIN10                                 52415
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE01                               52416
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE01B                              52417
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE02                               52418
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE02B                              52419
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE03                               52420
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE04                               52421
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE04B                              52422
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE05                               52423
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE06                               52424
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE06B                              52425
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE07                               52426
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE08                               52427
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE09                               52428
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE11                               52429
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE12                               52430
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE12B                              52431
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE13                               52432
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE14                               52433
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE14B                              52434
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE15                               52435
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE15B                              52436
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE16                               52437
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE16B                              52438
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE18                               52439
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE19                               52440
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE20                               52441
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE20B                              52442
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE21                               52443
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE22                               52444
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE23                               52445
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE24                               52446
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE26                               52447
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE26B                              52448
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE27                               52449
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE27B                              52450
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE28                               52451
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE28B                              52452
#define IDGS_TPCREWSPEECHZIRFC_FIRSTMATE29                               52453
#define IDGS_TPCREWSPEECHZIRFC_RIGGER03                                  52454
#define IDGS_TPCREWSPEECHZIRFC_RIGGER03B                                 52455
#define IDGS_TPCREWSPEECHZIRFC_RIGGER04                                  52456
#define IDGS_TPCREWSPEECHZIRFC_RIGGER04B                                 52457
#define IDGS_TPCREWSPEECHZIRFC_RIGGER05                                  52458
#define IDGS_TPCREWSPEECHZIRFC_RIGGER06                                  52459
