// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPFRONTENDTEXT01_ADD                                        52800
#define IDGS_TPFRONTENDTEXT01_ADVANCED_OPTIONS                           52801
#define IDGS_TPFRONTENDTEXT01_ASSEMBLE_FLEET                             52802
#define IDGS_TPFRONTENDTEXT01_AVAILABLE_CREW                             52803
#define IDGS_TPFRONTENDTEXT01_AVAILABLE_SHIPS                            52804
#define IDGS_TPFRONTENDTEXT01_AVAILABLE_SHIP_NAMES                       52805
#define IDGS_TPFRONTENDTEXT01_AVAILABLE_WEAPONS                          52806
#define IDGS_TPFRONTENDTEXT01_BACK                                       52807
#define IDGS_TPFRONTENDTEXT01_BAN                                        52808
#define IDGS_TPFRONTENDTEXT01_BANNED_BY_THE_SERVER                       52809
#define IDGS_TPFRONTENDTEXT01_CAMPAIGN                                   52810
#define IDGS_TPFRONTENDTEXT01_CLOSED                                     52811
#define IDGS_TPFRONTENDTEXT01_CLOSING                                    52812
#define IDGS_TPFRONTENDTEXT01_CODE                                       52813
#define IDGS_TPFRONTENDTEXT01_COMPUTER                                   52814
#define IDGS_TPFRONTENDTEXT01_CONTROL                                    52815
#define IDGS_TPFRONTENDTEXT01_COULD_NOT_LOAD_PROFILE                     52816
#define IDGS_TPFRONTENDTEXT01_CREW_DIALOGUE_VOLUME                       52817
#define IDGS_TPFRONTENDTEXT01_CURRENT_VICTORY_POINTS                     52818
#define IDGS_TPFRONTENDTEXT01_DEFAULT_GAME_NAME                          52819
#define IDGS_TPFRONTENDTEXT01_DISCONNECTED_FROM_THE_SERVER               52820
#define IDGS_TPFRONTENDTEXT01_EFFECT_VOLUME                              52821
#define IDGS_TPFRONTENDTEXT01_FLEET_SIZE_LIMIT                           52822
#define IDGS_TPFRONTENDTEXT01_FRIEND                                     52823
#define IDGS_TPFRONTENDTEXT01_FRIENDS_EDIT                               52824
#define IDGS_TPFRONTENDTEXT01_FRIENDS_NAME                               52825
#define IDGS_TPFRONTENDTEXT01_FRIEND_CODE                                52826
#define IDGS_TPFRONTENDTEXT01_GAME_SUMMARY                               52827
#define IDGS_TPFRONTENDTEXT01_GUNS                                       52828
#define IDGS_TPFRONTENDTEXT01_GUN_DAMAGE                                 52829
#define IDGS_TPFRONTENDTEXT01_GUN_EFFECTIVE_RANGE                        52830
#define IDGS_TPFRONTENDTEXT01_GUN_MAXIMUM_RANGE                          52831
#define IDGS_TPFRONTENDTEXT01_GUN_POINT_COST                             52832
#define IDGS_TPFRONTENDTEXT01_HISTORICAL                                 52833
#define IDGS_TPFRONTENDTEXT01_HUMAN                                      52834
#define IDGS_TPFRONTENDTEXT01_IM_READY                                   52835
#define IDGS_TPFRONTENDTEXT01_JOINING                                    52836
#define IDGS_TPFRONTENDTEXT01_KICK                                       52837
#define IDGS_TPFRONTENDTEXT01_KICKED_BY_THE_SERVER                       52838
#define IDGS_TPFRONTENDTEXT01_KMPH                                       52839
#define IDGS_TPFRONTENDTEXT01_LOAD                                       52840
#define IDGS_TPFRONTENDTEXT01_LOADING_SHIP_MODEL                         52841
#define IDGS_TPFRONTENDTEXT01_LOAD_GAME                                  52842
#define IDGS_TPFRONTENDTEXT01_METERS                                     52843
#define IDGS_TPFRONTENDTEXT01_MUSIC_VOLUME                               52844
#define IDGS_TPFRONTENDTEXT01_NA_STRING                                  52845
#define IDGS_TPFRONTENDTEXT01_NON_SELECTABLE                             52846
#define IDGS_TPFRONTENDTEXT01_OFF                                        52847
#define IDGS_TPFRONTENDTEXT01_ON                                         52848
#define IDGS_TPFRONTENDTEXT01_OPEN                                       52849
#define IDGS_TPFRONTENDTEXT01_OVERALL_VOLUME                             52850
#define IDGS_TPFRONTENDTEXT01_PING                                       52851
#define IDGS_TPFRONTENDTEXT01_PLAYERS                                    52852
#define IDGS_TPFRONTENDTEXT01_PLAYER_KILL_COUNT                          52853
#define IDGS_TPFRONTENDTEXT01_PLEASE_SELECT_A_RACE                       52854
#define IDGS_TPFRONTENDTEXT01_POSITIONS                                  52855
#define IDGS_TPFRONTENDTEXT01_PROFILES_ARMS                              52856
#define IDGS_TPFRONTENDTEXT01_PROFILES_CREW                              52857
#define IDGS_TPFRONTENDTEXT01_PROFILES_FLEET                             52858
#define IDGS_TPFRONTENDTEXT01_QUIT_GAME                                  52859
#define IDGS_TPFRONTENDTEXT01_SAVE                                       52860
#define IDGS_TPFRONTENDTEXT01_SAVED_CAMPAIGNS                            52861
#define IDGS_TPFRONTENDTEXT01_SAVE_GAME                                  52862
#define IDGS_TPFRONTENDTEXT01_SCREENS_BACK                               52863
#define IDGS_TPFRONTENDTEXT01_SCREENS_BASIC_TRAINING                     52864
#define IDGS_TPFRONTENDTEXT01_SCREENS_FULL_TRAINING                      52865
#define IDGS_TPFRONTENDTEXT01_SCREENS_LOAD_CAMPAIGN                      52866
#define IDGS_TPFRONTENDTEXT01_SCREENS_SELECT_A                           52867
#define IDGS_TPFRONTENDTEXT01_SCREENS_START_SKIRMISH                     52868
#define IDGS_TPFRONTENDTEXT01_SELECT_KEY                                 52869
#define IDGS_TPFRONTENDTEXT01_SERVER_GAME_TYPE                           52870
#define IDGS_TPFRONTENDTEXT01_SERVER_HOSTNAME                            52871
#define IDGS_TPFRONTENDTEXT01_SERVER_MAPNAME                             52872
#define IDGS_TPFRONTENDTEXT01_SERVER_PLAYER_NUMBER                       52873
#define IDGS_TPFRONTENDTEXT01_SINGLE_PLAYER                              52874
#define IDGS_TPFRONTENDTEXT01_SORT_BY                                    52875
#define IDGS_TPFRONTENDTEXT01_SOUNDDETAILLEVEL                           52876
#define IDGS_TPFRONTENDTEXT01_STATBAR_LABEL_MANEUVERABILITY              52877
#define IDGS_TPFRONTENDTEXT01_STATBAR_LABEL_REPAIR_RATE                  52878
#define IDGS_TPFRONTENDTEXT01_STATBAR_LABEL_SPEED                        52879
#define IDGS_TPFRONTENDTEXT01_STATBAR_LABEL_STRENGTH                     52880
#define IDGS_TPFRONTENDTEXT01_STATS_SCREEN                               52881
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_GAME                        52882
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_GAME_ALREADY_STARTED        52883
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_GAME_DATA_BAD               52884
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_GAME_DIFFERENT_VERSIONS     52885
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_GAME_FULL                   52886
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_INVALID_PASSWORD            52887
#define IDGS_TPFRONTENDTEXT01_UNABLE_TO_JOIN_PRIVATE_GAME                52888
#define IDGS_TPFRONTENDTEXT01_UNKNOWN_RACE                               52889
#define IDGS_TPFRONTENDTEXT01_VERSION                                    52890
#define IDGS_TPFRONTENDTEXT01_VERSION_ABBREVIATION                       52891
#define IDGS_TPFRONTENDTEXT01_VICTORY_POINTS_REMAINING                   52892
#define IDGS_TPFRONTENDTEXT01_VIEW_OPEN_MAPS                             52893
#define IDGS_TPFRONTENDTEXT01_VIEW_PRESET_MAPS                           52894
#define IDGS_TPFRONTENDTEXT01_WOULD_YOU_LIKE_TO_CONTINUE                 52895
#define IDGS_TPFRONTENDTEXT01_YOU_HAVE                                   52896
#define IDGS_TPFRONTENDTEXT01_YOU_HAVE_BEEN                              52897
