// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPFRONTENDTEXT_BUTTON_ADD                                   52700
#define IDGS_TPFRONTENDTEXT_BUTTON_ARMS                                  52701
#define IDGS_TPFRONTENDTEXT_BUTTON_CREW                                  52702
#define IDGS_TPFRONTENDTEXT_BUTTON_DROP                                  52703
#define IDGS_TPFRONTENDTEXT_BUTTON_SHIPS                                 52704
#define IDGS_TPFRONTENDTEXT_CREW                                         52705
#define IDGS_TPFRONTENDTEXT_CREWSKILL_COMBAT                             52706
#define IDGS_TPFRONTENDTEXT_CREWSKILL_ENGINEERING                        52707
#define IDGS_TPFRONTENDTEXT_CREWSKILL_GUNNERY                            52708
#define IDGS_TPFRONTENDTEXT_CREWSKILL_LEADERSHIP                         52709
#define IDGS_TPFRONTENDTEXT_CREWSKILL_NAVIGATION                         52710
#define IDGS_TPFRONTENDTEXT_CREWSKILL_RIGGING                            52711
#define IDGS_TPFRONTENDTEXT_CREWSKILL_SPOTTING                           52712
#define IDGS_TPFRONTENDTEXT_MANEUVERABILITY                              52713
#define IDGS_TPFRONTENDTEXT_MAX_SPEED                                    52714
#define IDGS_TPFRONTENDTEXT_SCREENS_ABORT_GAME                           52715
#define IDGS_TPFRONTENDTEXT_SCREENS_ADD                                  52716
#define IDGS_TPFRONTENDTEXT_SCREENS_ARMS                                 52717
#define IDGS_TPFRONTENDTEXT_SCREENS_ASSEMBLE_FLEET                       52718
#define IDGS_TPFRONTENDTEXT_SCREENS_AUDIO_OPTIONS                        52719
#define IDGS_TPFRONTENDTEXT_SCREENS_AUTO_ASSIGN                          52720
#define IDGS_TPFRONTENDTEXT_SCREENS_BACKTOLOBBY                          52721
#define IDGS_TPFRONTENDTEXT_SCREENS_BLACK_HOLE                           52722
#define IDGS_TPFRONTENDTEXT_SCREENS_BUTTON                               52723
#define IDGS_TPFRONTENDTEXT_SCREENS_CANCEL                               52724
#define IDGS_TPFRONTENDTEXT_SCREENS_CLOSE                                52725
#define IDGS_TPFRONTENDTEXT_SCREENS_CLOSE_MENU                           52726
#define IDGS_TPFRONTENDTEXT_SCREENS_CONNECTION_LOST                      52727
#define IDGS_TPFRONTENDTEXT_SCREENS_CONTINUE                             52728
#define IDGS_TPFRONTENDTEXT_SCREENS_CONTROL                              52729
#define IDGS_TPFRONTENDTEXT_SCREENS_CONTROL_OPTIONS                      52730
#define IDGS_TPFRONTENDTEXT_SCREENS_CREATE                               52731
#define IDGS_TPFRONTENDTEXT_SCREENS_CREATE_GAME                          52732
#define IDGS_TPFRONTENDTEXT_SCREENS_CREW                                 52733
#define IDGS_TPFRONTENDTEXT_SCREENS_DEFAULT_NAME                         52734
#define IDGS_TPFRONTENDTEXT_SCREENS_DISPLAY_OPTIONS                      52735
#define IDGS_TPFRONTENDTEXT_SCREENS_DROP                                 52736
#define IDGS_TPFRONTENDTEXT_SCREENS_EFFECT_DETAIL                        52737
#define IDGS_TPFRONTENDTEXT_SCREENS_ERROR_FLAG                           52738
#define IDGS_TPFRONTENDTEXT_SCREENS_ERROR_FLEET                          52739
#define IDGS_TPFRONTENDTEXT_SCREENS_EXIT_STATS_SCREEN                    52740
#define IDGS_TPFRONTENDTEXT_SCREENS_FILENAME                             52741
#define IDGS_TPFRONTENDTEXT_SCREENS_GAME_LOBBY                           52742
#define IDGS_TPFRONTENDTEXT_SCREENS_HOST_NAME                            52743
#define IDGS_TPFRONTENDTEXT_SCREENS_INTERNET                             52744
#define IDGS_TPFRONTENDTEXT_SCREENS_JOIN                                 52745
#define IDGS_TPFRONTENDTEXT_SCREENS_LAN                                  52746
#define IDGS_TPFRONTENDTEXT_SCREENS_LAUNCH_GAME                          52747
#define IDGS_TPFRONTENDTEXT_SCREENS_LOAD                                 52748
#define IDGS_TPFRONTENDTEXT_SCREENS_LOADING                              52749
#define IDGS_TPFRONTENDTEXT_SCREENS_LOAD_ARMS                            52750
#define IDGS_TPFRONTENDTEXT_SCREENS_LOAD_CREW                            52751
#define IDGS_TPFRONTENDTEXT_SCREENS_LOAD_FLEET                           52752
#define IDGS_TPFRONTENDTEXT_SCREENS_METEOR_STORM                         52753
#define IDGS_TPFRONTENDTEXT_SCREENS_MODEL_DETAIL                         52754
#define IDGS_TPFRONTENDTEXT_SCREENS_MULTIPLAYER                          52755
#define IDGS_TPFRONTENDTEXT_SCREENS_NEBULA_EFFECT                        52756
#define IDGS_TPFRONTENDTEXT_SCREENS_NEXT_LEVEL                           52757
#define IDGS_TPFRONTENDTEXT_SCREENS_NULL                                 52758
#define IDGS_TPFRONTENDTEXT_SCREENS_OK                                   52759
#define IDGS_TPFRONTENDTEXT_SCREENS_OPTIONS                              52760
#define IDGS_TPFRONTENDTEXT_SCREENS_PASSWORD                             52761
#define IDGS_TPFRONTENDTEXT_SCREENS_PLAYER                               52762
#define IDGS_TPFRONTENDTEXT_SCREENS_PRESS_A_KEY                          52763
#define IDGS_TPFRONTENDTEXT_SCREENS_PROFILES                             52764
#define IDGS_TPFRONTENDTEXT_SCREENS_QUIT                                 52765
#define IDGS_TPFRONTENDTEXT_SCREENS_REMOVE                               52766
#define IDGS_TPFRONTENDTEXT_SCREENS_RENDERER_AND_BIT_DEPTH               52767
#define IDGS_TPFRONTENDTEXT_SCREENS_RENDER_BACKGROUND                    52768
#define IDGS_TPFRONTENDTEXT_SCREENS_RESTORE_DEFAULTS                     52769
#define IDGS_TPFRONTENDTEXT_SCREENS_SAVE                                 52770
#define IDGS_TPFRONTENDTEXT_SCREENS_SAVE_ARMS                            52771
#define IDGS_TPFRONTENDTEXT_SCREENS_SAVE_CREW                            52772
#define IDGS_TPFRONTENDTEXT_SCREENS_SAVE_FLEET                           52773
#define IDGS_TPFRONTENDTEXT_SCREENS_SELECT_GAME                          52774
#define IDGS_TPFRONTENDTEXT_SCREENS_SHIPS                                52775
#define IDGS_TPFRONTENDTEXT_SCREENS_SHIP_WAKES                           52776
#define IDGS_TPFRONTENDTEXT_SCREENS_SINGLE_PLAYER                        52777
#define IDGS_TPFRONTENDTEXT_SCREENS_SKIRMISH                             52778
#define IDGS_TPFRONTENDTEXT_SCREENS_SOLAR_STORM                          52779
#define IDGS_TPFRONTENDTEXT_SCREENS_SOUND_OPTIONS                        52780
#define IDGS_TPFRONTENDTEXT_SCREENS_START_GAME                           52781
#define IDGS_TPFRONTENDTEXT_SCREENS_START_NEW_CAMPAIGN                   52782
#define IDGS_TPFRONTENDTEXT_SCREENS_TEXTURE_DETAIL                       52783
#define IDGS_TPFRONTENDTEXT_SCREENS_TUTORIAL                             52784
#define IDGS_TPFRONTENDTEXT_SCREENS_TYPE_IN_YOUR_NAME                    52785
#define IDGS_TPFRONTENDTEXT_SCREENS_VICTORYPOINTS                        52786
#define IDGS_TPFRONTENDTEXT_SCREENS_VICTORY_LIMIT                        52787
#define IDGS_TPFRONTENDTEXT_SCREENS_VIEW_PRESET_MAPS                     52788
#define IDGS_TPFRONTENDTEXT_SHIP_HITPOINTS                               52789
#define IDGS_TPFRONTENDTEXT_SHIP_MOUNTS_HEAVY                            52790
#define IDGS_TPFRONTENDTEXT_SHIP_MOUNTS_LIGHT                            52791
#define IDGS_TPFRONTENDTEXT_SHIP_MOUNTS_MEDIUM                           52792
#define IDGS_TPFRONTENDTEXT_SHIP_MOUNTS_SPECIAL                          52793
#define IDGS_TPFRONTENDTEXT_TURNINGRATE_AVERAGE                          52794
#define IDGS_TPFRONTENDTEXT_TURNINGRATE_GOOD                             52795
#define IDGS_TPFRONTENDTEXT_TURNINGRATE_POOR                             52796
#define IDGS_TPFRONTENDTEXT_TURNINGRATE_VERYGOOD                         52797
#define IDGS_TPFRONTENDTEXT_TURNINGRATE_VERYPOOR                         52798
#define IDGS_TPFRONTENDTEXT_VICTORY_POINTS                               52799
