// Generated on: 9/16/2002 6:25:22 PM
#define IDGS_TPFRONTENDTEXT03_ACTION                                     53000
#define IDGS_TPFRONTENDTEXT03_ALWAYS_FOCUS_SELECTED_SHIP                 53001
#define IDGS_TPFRONTENDTEXT03_ALWAYS_OFF                                 53002
#define IDGS_TPFRONTENDTEXT03_ALWAYS_ON                                  53003
#define IDGS_TPFRONTENDTEXT03_CAMPAIGN_DIFFICULTY_LEVEL                  53004
#define IDGS_TPFRONTENDTEXT03_CONTROL_OPTIONS_1_OF_2                     53005
#define IDGS_TPFRONTENDTEXT03_CONTROL_OPTIONS_2_OF_2                     53006
#define IDGS_TPFRONTENDTEXT03_CREATE_FIRST_PLAYER_PROFILE                53007
#define IDGS_TPFRONTENDTEXT03_DIFFICULTY_LEVEL                           53008
#define IDGS_TPFRONTENDTEXT03_DISPLAY_BACKGROUND                         53009
#define IDGS_TPFRONTENDTEXT03_DISPLAY_STARS                              53010
#define IDGS_TPFRONTENDTEXT03_EASY                                       53011
#define IDGS_TPFRONTENDTEXT03_ENGINEERS                                  53012
#define IDGS_TPFRONTENDTEXT03_FIGHTERS                                   53013
#define IDGS_TPFRONTENDTEXT03_FLAG                                       53014
#define IDGS_TPFRONTENDTEXT03_FLEET                                      53015
#define IDGS_TPFRONTENDTEXT03_FLEET_NAVY                                 53016
#define IDGS_TPFRONTENDTEXT03_FLEET_PIRATE                               53017
#define IDGS_TPFRONTENDTEXT03_FLEET_PROCYON                              53018
#define IDGS_TPFRONTENDTEXT03_FULL_EFFECTS_ALWAYS                        53019
#define IDGS_TPFRONTENDTEXT03_GUNNERS                                    53020
#define IDGS_TPFRONTENDTEXT03_GUN_SINGULAR                               53021
#define IDGS_TPFRONTENDTEXT03_HARD                                       53022
#define IDGS_TPFRONTENDTEXT03_NORMAL                                     53023
#define IDGS_TPFRONTENDTEXT03_ON_WHEN_CLOSE                              53024
#define IDGS_TPFRONTENDTEXT03_ON_WHEN_FAR                                53025
#define IDGS_TPFRONTENDTEXT03_OPTION_PLAY_DEATH_ANIMATIONS               53026
#define IDGS_TPFRONTENDTEXT03_PLAYER_1                                   53027
#define IDGS_TPFRONTENDTEXT03_PLAYER_2                                   53028
#define IDGS_TPFRONTENDTEXT03_PLAYER_3                                   53029
#define IDGS_TPFRONTENDTEXT03_PLAYER_4                                   53030
#define IDGS_TPFRONTENDTEXT03_PLAYER_5                                   53031
#define IDGS_TPFRONTENDTEXT03_PLAYER_6                                   53032
#define IDGS_TPFRONTENDTEXT03_PLAYER_7                                   53033
#define IDGS_TPFRONTENDTEXT03_PLAYER_8                                   53034
#define IDGS_TPFRONTENDTEXT03_PLAYER_PROFILES_PART_1_OF_2                53035
#define IDGS_TPFRONTENDTEXT03_PLAYER_PROFILES_PART_2_OF_2                53036
#define IDGS_TPFRONTENDTEXT03_RIGGERS                                    53037
#define IDGS_TPFRONTENDTEXT03_SHIP_BANNERS                               53038
#define IDGS_TPFRONTENDTEXT03_SINGLEPLAYER_DIFFICULTY_LEVEL              53039
#define IDGS_TPFRONTENDTEXT03_SOUND_CHANNELS                             53040
#define IDGS_TPFRONTENDTEXT03_THE_HOST_HAS_CHANGED_YOUR_TEAM             53041
#define IDGS_TPFRONTENDTEXT03_UNABLE_TO_FIND_MATCHING_SERVER             53042
