// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPJOURNALSCREEN_DUMMY_TITLE                                 53600
#define IDGS_TPJOURNALSCREEN_EXIT                                        53601
#define IDGS_TPJOURNALSCREEN_MISSION10_JOURNALTITLE                      53602
#define IDGS_TPJOURNALSCREEN_MISSION11_JOURNALTITLE                      53603
#define IDGS_TPJOURNALSCREEN_MISSION12_JOURNALTITLE                      53604
#define IDGS_TPJOURNALSCREEN_MISSION1_JOURNALTITLE                       53605
#define IDGS_TPJOURNALSCREEN_MISSION2_JOURNALTITLE                       53606
#define IDGS_TPJOURNALSCREEN_MISSION3_JOURNALTITLE                       53607
#define IDGS_TPJOURNALSCREEN_MISSION4_JOURNALTITLE                       53608
#define IDGS_TPJOURNALSCREEN_MISSION5_JOURNALTITLE                       53609
#define IDGS_TPJOURNALSCREEN_MISSION6_JOURNALTITLE                       53610
#define IDGS_TPJOURNALSCREEN_MISSION7_JOURNALTITLE                       53611
#define IDGS_TPJOURNALSCREEN_MISSION8_JOURNALTITLE                       53612
#define IDGS_TPJOURNALSCREEN_MISSION9_JOURNALTITLE                       53613
#define IDGS_TPJOURNALSCREEN_NEXT                                        53614
#define IDGS_TPJOURNALSCREEN_PREV                                        53615
