// Generated on: 08/09/2002 10:24:08 PM
#define IDGS_TPSHIPNAMENAVY01_AGINCOURT                                  54100
#define IDGS_TPSHIPNAMENAVY01_APHRODITE                                  54101
#define IDGS_TPSHIPNAMENAVY01_ARTEMIS                                    54102
#define IDGS_TPSHIPNAMENAVY01_ASHCROFT                                   54103
#define IDGS_TPSHIPNAMENAVY01_ATHENA                                     54104
#define IDGS_TPSHIPNAMENAVY01_BAILY                                      54105
#define IDGS_TPSHIPNAMENAVY01_BALLISTRADE                                54106
#define IDGS_TPSHIPNAMENAVY01_BARBICAN                                   54107
#define IDGS_TPSHIPNAMENAVY01_BASTION                                    54108
#define IDGS_TPSHIPNAMENAVY01_BASTOGNE                                   54109
#define IDGS_TPSHIPNAMENAVY01_BATTLEMENT                                 54110
#define IDGS_TPSHIPNAMENAVY01_BOUNTY                                     54111
#define IDGS_TPSHIPNAMENAVY01_CARTIER                                    54112
#define IDGS_TPSHIPNAMENAVY01_CASTLE                                     54113
#define IDGS_TPSHIPNAMENAVY01_CHAMPLAIN                                  54114
#define IDGS_TPSHIPNAMENAVY01_CHILLIWACK                                 54115
#define IDGS_TPSHIPNAMENAVY01_CITADEL                                    54116
#define IDGS_TPSHIPNAMENAVY01_CLARK                                      54117
#define IDGS_TPSHIPNAMENAVY01_COLUMBUS                                   54118
#define IDGS_TPSHIPNAMENAVY01_CONRAD                                     54119
#define IDGS_TPSHIPNAMENAVY01_COOK                                       54120
#define IDGS_TPSHIPNAMENAVY01_CORNUCOPIA                                 54121
#define IDGS_TPSHIPNAMENAVY01_DELEON                                     54122
#define IDGS_TPSHIPNAMENAVY01_DIANA                                      54123
#define IDGS_TPSHIPNAMENAVY01_DIEPPE                                     54124
#define IDGS_TPSHIPNAMENAVY01_DUNKIRK                                    54125
#define IDGS_TPSHIPNAMENAVY01_EDEN                                       54126
#define IDGS_TPSHIPNAMENAVY01_ELALEMEIN                                  54127
#define IDGS_TPSHIPNAMENAVY01_FORTRESS                                   54128
#define IDGS_TPSHIPNAMENAVY01_FREJA                                      54129
#define IDGS_TPSHIPNAMENAVY01_HASTINGS                                   54130
#define IDGS_TPSHIPNAMENAVY01_HECATE                                     54131
#define IDGS_TPSHIPNAMENAVY01_HERA                                       54132
#define IDGS_TPSHIPNAMENAVY01_ISIS                                       54133
#define IDGS_TPSHIPNAMENAVY01_JUNO                                       54134
#define IDGS_TPSHIPNAMENAVY01_KAMLOOPS                                   54135
#define IDGS_TPSHIPNAMENAVY01_KEEP                                       54136
#define IDGS_TPSHIPNAMENAVY01_KITIMAT                                    54137
#define IDGS_TPSHIPNAMENAVY01_KURSK                                      54138
#define IDGS_TPSHIPNAMENAVY01_LEXINGTON                                  54139
#define IDGS_TPSHIPNAMENAVY01_LOUIS                                      54140
#define IDGS_TPSHIPNAMENAVY01_LYTTON                                     54141
#define IDGS_TPSHIPNAMENAVY01_MAGELLAN                                   54142
#define IDGS_TPSHIPNAMENAVY01_MERCY                                      54143
#define IDGS_TPSHIPNAMENAVY01_MERRIT                                     54144
#define IDGS_TPSHIPNAMENAVY01_MINERVA                                    54145
#define IDGS_TPSHIPNAMENAVY01_NANAIMO                                    54146
#define IDGS_TPSHIPNAMENAVY01_PERSEPHONE                                 54147
#define IDGS_TPSHIPNAMENAVY01_PLENITUDE                                  54148
#define IDGS_TPSHIPNAMENAVY01_PLENTY                                     54149
#define IDGS_TPSHIPNAMENAVY01_PRINCEGEORGE                               54150
#define IDGS_TPSHIPNAMENAVY01_PRINCERUPERT                               54151
#define IDGS_TPSHIPNAMENAVY01_PROVIDENCE                                 54152
#define IDGS_TPSHIPNAMENAVY01_RALEIGH                                    54153
#define IDGS_TPSHIPNAMENAVY01_RESOURCE                                   54154
#define IDGS_TPSHIPNAMENAVY01_ROOK                                       54155
#define IDGS_TPSHIPNAMENAVY01_SARATOGA                                   54156
#define IDGS_TPSHIPNAMENAVY01_SHACKLETON                                 54157
#define IDGS_TPSHIPNAMENAVY01_SHANGRILA                                  54158
#define IDGS_TPSHIPNAMENAVY01_SIF                                        54159
#define IDGS_TPSHIPNAMENAVY01_SOMME                                      54160
#define IDGS_TPSHIPNAMENAVY01_STREGANONA                                 54161
#define IDGS_TPSHIPNAMENAVY01_SUCCESS                                    54162
#define IDGS_TPSHIPNAMENAVY01_TOWER                                      54163
#define IDGS_TPSHIPNAMENAVY01_TURRET                                     54164
#define IDGS_TPSHIPNAMENAVY01_VALHALLA                                   54165
#define IDGS_TPSHIPNAMENAVY01_VANCOUVER                                  54166
#define IDGS_TPSHIPNAMENAVY01_VENUS                                      54167
#define IDGS_TPSHIPNAMENAVY01_VERNON                                     54168
#define IDGS_TPSHIPNAMENAVY01_VESPUCCI                                   54169
#define IDGS_TPSHIPNAMENAVY01_VICTORIA                                   54170
#define IDGS_TPSHIPNAMENAVY01_WATERLOO                                   54171
#define IDGS_TPSHIPNAMENAVY01_ZAFTIG                                     54172
