// Generated on: 08/09/2002 10:24:37 PM
#define IDGS_TPSHIPNAMEPROCYON01_ADAMANTIUM                              54500
#define IDGS_TPSHIPNAMEPROCYON01_AMETHYST                                54501
#define IDGS_TPSHIPNAMEPROCYON01_ARROWFLIGHT                             54502
#define IDGS_TPSHIPNAMEPROCYON01_CARTASA                                 54503
#define IDGS_TPSHIPNAMEPROCYON01_COLOSSUS                                54504
#define IDGS_TPSHIPNAMEPROCYON01_DEALENN                                 54505
#define IDGS_TPSHIPNAMEPROCYON01_DESTRUCTION                             54506
#define IDGS_TPSHIPNAMEPROCYON01_DEVASTATION                             54507
#define IDGS_TPSHIPNAMEPROCYON01_DIAMOND                                 54508
#define IDGS_TPSHIPNAMEPROCYON01_DOMINATION                              54509
#define IDGS_TPSHIPNAMEPROCYON01_EXTERMINATION                           54510
#define IDGS_TPSHIPNAMEPROCYON01_FARSPEAK                                54511
#define IDGS_TPSHIPNAMEPROCYON01_FROSTKNIFE                              54512
#define IDGS_TPSHIPNAMEPROCYON01_GIKAR                                   54513
#define IDGS_TPSHIPNAMEPROCYON01_GIQUAN                                  54514
#define IDGS_TPSHIPNAMEPROCYON01_GLADIATOR                               54515
#define IDGS_TPSHIPNAMEPROCYON01_HAILFIST                                54516
#define IDGS_TPSHIPNAMEPROCYON01_HURRICANE                               54517
#define IDGS_TPSHIPNAMEPROCYON01_ICEFERRET                               54518
#define IDGS_TPSHIPNAMEPROCYON01_IMPERATOR                               54519
#define IDGS_TPSHIPNAMEPROCYON01_IVINOVA                                 54520
#define IDGS_TPSHIPNAMEPROCYON01_JADE                                    54521
#define IDGS_TPSHIPNAMEPROCYON01_KORSH                                   54522
#define IDGS_TPSHIPNAMEPROCYON01_LENEAR                                  54523
#define IDGS_TPSHIPNAMEPROCYON01_MOLAREE                                 54524
#define IDGS_TPSHIPNAMEPROCYON01_MORDIN                                  54525
#define IDGS_TPSHIPNAMEPROCYON01_NOVAMACE                                54526
#define IDGS_TPSHIPNAMEPROCYON01_OBLITERATION                            54527
#define IDGS_TPSHIPNAMEPROCYON01_OWL                                     54528
#define IDGS_TPSHIPNAMEPROCYON01_PITCHSNAKE                              54529
#define IDGS_TPSHIPNAMEPROCYON01_REDIC                                   54530
#define IDGS_TPSHIPNAMEPROCYON01_RETALIATION                             54531
#define IDGS_TPSHIPNAMEPROCYON01_RUBY                                    54532
#define IDGS_TPSHIPNAMEPROCYON01_SALAMANDER                              54533
#define IDGS_TPSHIPNAMEPROCYON01_SCRY                                    54534
#define IDGS_TPSHIPNAMEPROCYON01_SHEERRAZOR                              54535
#define IDGS_TPSHIPNAMEPROCYON01_SHERRODAN                               54536
#define IDGS_TPSHIPNAMEPROCYON01_SHOCKBOW                                54537
#define IDGS_TPSHIPNAMEPROCYON01_SNOWMONKEY                              54538
#define IDGS_TPSHIPNAMEPROCYON01_STALKER                                 54539
#define IDGS_TPSHIPNAMEPROCYON01_STARFISH                                54540
#define IDGS_TPSHIPNAMEPROCYON01_STARHUNTER                              54541
#define IDGS_TPSHIPNAMEPROCYON01_STAROPAL                                54542
#define IDGS_TPSHIPNAMEPROCYON01_STEALTHBLADE                            54543
#define IDGS_TPSHIPNAMEPROCYON01_STORMSHIELD                             54544
#define IDGS_TPSHIPNAMEPROCYON01_SUBJUGATION                             54545
#define IDGS_TPSHIPNAMEPROCYON01_TERROR                                  54546
#define IDGS_TPSHIPNAMEPROCYON01_TIASHA                                  54547
#define IDGS_TPSHIPNAMEPROCYON01_TITANIUM                                54548
#define IDGS_TPSHIPNAMEPROCYON01_VANADIUM                                54549
#define IDGS_TPSHIPNAMEPROCYON01_VEERE                                   54550
#define IDGS_TPSHIPNAMEPROCYON01_VIPER                                   54551
#define IDGS_TPSHIPNAMEPROCYON01_WARBARRAGE                              54552
#define IDGS_TPSHIPNAMEPROCYON01_WINDDAGGER                              54553
#define IDGS_TPSHIPNAMEPROCYON01_WINDRUSH                                54554
#define IDGS_TPSHIPNAMEPROCYON01_WINGSWIFT                               54555
