// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPSHIPNAMENAVY00_ADAMENT                                    54000
#define IDGS_TPSHIPNAMENAVY00_ADMIRALPIKE                                54001
#define IDGS_TPSHIPNAMENAVY00_ALPHA                                      54002
#define IDGS_TPSHIPNAMENAVY00_AMBITIOUS                                  54003
#define IDGS_TPSHIPNAMENAVY00_ARGUS                                      54004
#define IDGS_TPSHIPNAMENAVY00_ATTENTIVE                                  54005
#define IDGS_TPSHIPNAMENAVY00_AUDACIOUS                                  54006
#define IDGS_TPSHIPNAMENAVY00_AVALON                                     54007
#define IDGS_TPSHIPNAMENAVY00_BETA                                       54008
#define IDGS_TPSHIPNAMENAVY00_BITER                                      54009
#define IDGS_TPSHIPNAMENAVY00_BLAKE                                      54010
#define IDGS_TPSHIPNAMENAVY00_BOUNTY                                     54011
#define IDGS_TPSHIPNAMENAVY00_BROADSWORD                                 54012
#define IDGS_TPSHIPNAMENAVY00_BURKE                                      54013
#define IDGS_TPSHIPNAMENAVY00_CENTURION                                  54014
#define IDGS_TPSHIPNAMENAVY00_CHAMPION                                   54015
#define IDGS_TPSHIPNAMENAVY00_COMET                                      54016
#define IDGS_TPSHIPNAMENAVY00_COURAGEOUS                                 54017
#define IDGS_TPSHIPNAMENAVY00_CRICKET                                    54018
#define IDGS_TPSHIPNAMENAVY00_CRUSADER                                   54019
#define IDGS_TPSHIPNAMENAVY00_DELTA                                      54020
#define IDGS_TPSHIPNAMENAVY00_DISCOVERY                                  54021
#define IDGS_TPSHIPNAMENAVY00_DRAKE                                      54022
#define IDGS_TPSHIPNAMENAVY00_DRUM                                       54023
#define IDGS_TPSHIPNAMENAVY00_EMERALD                                    54024
#define IDGS_TPSHIPNAMENAVY00_ENDEAVOR                                   54025
#define IDGS_TPSHIPNAMENAVY00_ENDURANCE                                  54026
#define IDGS_TPSHIPNAMENAVY00_EPSILON                                    54027
#define IDGS_TPSHIPNAMENAVY00_ESSEX                                      54028
#define IDGS_TPSHIPNAMENAVY00_ETA                                        54029
#define IDGS_TPSHIPNAMENAVY00_EXETER                                     54030
#define IDGS_TPSHIPNAMENAVY00_EXMOORE                                    54031
#define IDGS_TPSHIPNAMENAVY00_EXPLORER                                   54032
#define IDGS_TPSHIPNAMENAVY00_FARRAGUT                                   54033
#define IDGS_TPSHIPNAMENAVY00_FERVENT                                    54034
#define IDGS_TPSHIPNAMENAVY00_FORMIDABLE                                 54035
#define IDGS_TPSHIPNAMENAVY00_FURIOUS                                    54036
#define IDGS_TPSHIPNAMENAVY00_GADFLY                                     54037
#define IDGS_TPSHIPNAMENAVY00_GALATEA                                    54038
#define IDGS_TPSHIPNAMENAVY00_GALAXY                                     54039
#define IDGS_TPSHIPNAMENAVY00_GAMMA                                      54040
#define IDGS_TPSHIPNAMENAVY00_GLORIOUS                                   54041
#define IDGS_TPSHIPNAMENAVY00_GLOWWORM                                   54042
#define IDGS_TPSHIPNAMENAVY00_GRAYBACK                                   54043
#define IDGS_TPSHIPNAMENAVY00_HANCOCK                                    54044
#define IDGS_TPSHIPNAMENAVY00_HOOD                                       54045
#define IDGS_TPSHIPNAMENAVY00_HOPE                                       54046
#define IDGS_TPSHIPNAMENAVY00_ILLUSTRIOUS                                54047
#define IDGS_TPSHIPNAMENAVY00_IMPERIAL                                   54048
#define IDGS_TPSHIPNAMENAVY00_IMPERVIOUS                                 54049
#define IDGS_TPSHIPNAMENAVY00_INDEFATIGABLE                              54050
#define IDGS_TPSHIPNAMENAVY00_INTREPID                                   54051
#define IDGS_TPSHIPNAMENAVY00_IOTA                                       54052
#define IDGS_TPSHIPNAMENAVY00_IRRESISTIBLE                               54053
#define IDGS_TPSHIPNAMENAVY00_JUPITER                                    54054
#define IDGS_TPSHIPNAMENAVY00_KAPPA                                      54055
#define IDGS_TPSHIPNAMENAVY00_KINGALEXANDERIII                           54056
#define IDGS_TPSHIPNAMENAVY00_LAMDA                                      54057
#define IDGS_TPSHIPNAMENAVY00_LEXINGTON                                  54058
#define IDGS_TPSHIPNAMENAVY00_LIBERTY                                    54059
#define IDGS_TPSHIPNAMENAVY00_LIGHTNING                                  54060
#define IDGS_TPSHIPNAMENAVY00_LOYALTY                                    54061
#define IDGS_TPSHIPNAMENAVY00_MAJESTIC                                   54062
#define IDGS_TPSHIPNAMENAVY00_MARATHON                                   54063
#define IDGS_TPSHIPNAMENAVY00_MERITORIOUS                                54064
#define IDGS_TPSHIPNAMENAVY00_MONARCH                                    54065
#define IDGS_TPSHIPNAMENAVY00_MU                                         54066
#define IDGS_TPSHIPNAMENAVY00_NEPTUNE                                    54067
#define IDGS_TPSHIPNAMENAVY00_OBERON                                     54068
#define IDGS_TPSHIPNAMENAVY00_PALADIN                                    54069
#define IDGS_TPSHIPNAMENAVY00_QUEENCATHERINEIV                           54070
#define IDGS_TPSHIPNAMENAVY00_RENOWN                                     54071
#define IDGS_TPSHIPNAMENAVY00_REPULSE                                    54072
#define IDGS_TPSHIPNAMENAVY00_ROANOKE                                    54073
#define IDGS_TPSHIPNAMENAVY00_ROYALSOVEREIGN                             54074
#define IDGS_TPSHIPNAMENAVY00_SIMS                                       54075
#define IDGS_TPSHIPNAMENAVY00_SIREN                                      54076
#define IDGS_TPSHIPNAMENAVY00_STARBURST                                  54077
#define IDGS_TPSHIPNAMENAVY00_STARFINDER                                 54078
#define IDGS_TPSHIPNAMENAVY00_STINGER                                    54079
#define IDGS_TPSHIPNAMENAVY00_SUCCESS                                    54080
#define IDGS_TPSHIPNAMENAVY00_SWALLOW                                    54081
#define IDGS_TPSHIPNAMENAVY00_SWIFTSURE                                  54082
#define IDGS_TPSHIPNAMENAVY00_TEMPEST                                    54083
#define IDGS_TPSHIPNAMENAVY00_TENACIOUS                                  54084
#define IDGS_TPSHIPNAMENAVY00_THETA                                      54085
#define IDGS_TPSHIPNAMENAVY00_TRITION                                    54086
#define IDGS_TPSHIPNAMENAVY00_TRIUMPH                                    54087
#define IDGS_TPSHIPNAMENAVY00_UNION                                      54088
#define IDGS_TPSHIPNAMENAVY00_VALLIANT                                   54089
#define IDGS_TPSHIPNAMENAVY00_VANGUARD                                   54090
#define IDGS_TPSHIPNAMENAVY00_VICTORIOUS                                 54091
#define IDGS_TPSHIPNAMENAVY00_VICTORY                                    54092
#define IDGS_TPSHIPNAMENAVY00_VORACIOUS                                  54093
#define IDGS_TPSHIPNAMENAVY00_WARSPITE                                   54094
#define IDGS_TPSHIPNAMENAVY00_WASP                                       54095
#define IDGS_TPSHIPNAMENAVY00_WILDCAT                                    54096
#define IDGS_TPSHIPNAMENAVY00_ZELOUS                                     54097
#define IDGS_TPSHIPNAMENAVY00_ZETA                                       54098
