// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPSHIPNAMEPIRATE00_ACEOFSPADES                              54200
#define IDGS_TPSHIPNAMEPIRATE00_AGAINSTALLODDS                           54201
#define IDGS_TPSHIPNAMEPIRATE00_ALEXSSTASH                               54202
#define IDGS_TPSHIPNAMEPIRATE00_ARGENTUM                                 54203
#define IDGS_TPSHIPNAMEPIRATE00_BACHELORSDELIGHT                         54204
#define IDGS_TPSHIPNAMEPIRATE00_BACKSTAB                                 54205
#define IDGS_TPSHIPNAMEPIRATE00_BANSHEE                                  54206
#define IDGS_TPSHIPNAMEPIRATE00_BARROZO                                  54207
#define IDGS_TPSHIPNAMEPIRATE00_BENBOWROVER                              54208
#define IDGS_TPSHIPNAMEPIRATE00_BLACKBELAMY                              54209
#define IDGS_TPSHIPNAMEPIRATE00_BLACKWIDOW                               54210
#define IDGS_TPSHIPNAMEPIRATE00_BONNECHANCE                              54211
#define IDGS_TPSHIPNAMEPIRATE00_BRAVO                                    54212
#define IDGS_TPSHIPNAMEPIRATE00_CALLICOJACK                              54213
#define IDGS_TPSHIPNAMEPIRATE00_CALLIOPE                                 54214
#define IDGS_TPSHIPNAMEPIRATE00_CALSHOTSPIT                              54215
#define IDGS_TPSHIPNAMEPIRATE00_CASSANDRA                                54216
#define IDGS_TPSHIPNAMEPIRATE00_CHRISTOPHERSCHANCE                       54217
#define IDGS_TPSHIPNAMEPIRATE00_COBRA                                    54218
#define IDGS_TPSHIPNAMEPIRATE00_CUTTYSHARK                               54219
#define IDGS_TPSHIPNAMEPIRATE00_DARKJOKE                                 54220
#define IDGS_TPSHIPNAMEPIRATE00_DECEPTION                                54221
#define IDGS_TPSHIPNAMEPIRATE00_DEGRASSE                                 54222
#define IDGS_TPSHIPNAMEPIRATE00_DESIRE                                   54223
#define IDGS_TPSHIPNAMEPIRATE00_DIRTYRAT                                 54224
#define IDGS_TPSHIPNAMEPIRATE00_DOYLESHOPE                               54225
#define IDGS_TPSHIPNAMEPIRATE00_EXILE                                    54226
#define IDGS_TPSHIPNAMEPIRATE00_FALCON                                   54227
#define IDGS_TPSHIPNAMEPIRATE00_FANCYSCOT                                54228
#define IDGS_TPSHIPNAMEPIRATE00_FENIANRAM                                54229
#define IDGS_TPSHIPNAMEPIRATE00_FERRET                                   54230
#define IDGS_TPSHIPNAMEPIRATE00_FLAMINGROSE                              54231
#define IDGS_TPSHIPNAMEPIRATE00_FLYINGCLOUD                              54232
#define IDGS_TPSHIPNAMEPIRATE00_FLYINGKING                               54233
#define IDGS_TPSHIPNAMEPIRATE00_FORFEIT                                  54234
#define IDGS_TPSHIPNAMEPIRATE00_FORTGRANGE                               54235
#define IDGS_TPSHIPNAMEPIRATE00_FORTUNE                                  54236
#define IDGS_TPSHIPNAMEPIRATE00_FURIOUS                                  54237
#define IDGS_TPSHIPNAMEPIRATE00_GAMBLERSLUCK                             54238
#define IDGS_TPSHIPNAMEPIRATE00_GANGSTEROFLOVE                           54239
#define IDGS_TPSHIPNAMEPIRATE00_GIFT                                     54240
#define IDGS_TPSHIPNAMEPIRATE00_GOLDENHIND                               54241
#define IDGS_TPSHIPNAMEPIRATE00_GORGON                                   54242
#define IDGS_TPSHIPNAMEPIRATE00_HALIFAXBOB                               54243
#define IDGS_TPSHIPNAMEPIRATE00_HAPPYDELIVERY                            54244
#define IDGS_TPSHIPNAMEPIRATE00_HELENA                                   54245
#define IDGS_TPSHIPNAMEPIRATE00_HIGHLANDCHIEF                            54246
#define IDGS_TPSHIPNAMEPIRATE00_HORNET                                   54247
#define IDGS_TPSHIPNAMEPIRATE00_HUDSONREX                                54248
#define IDGS_TPSHIPNAMEPIRATE00_HURLYBURLY                               54249
#define IDGS_TPSHIPNAMEPIRATE00_HYDRA                                    54250
#define IDGS_TPSHIPNAMEPIRATE00_JACKOFCLUBS                              54251
#define IDGS_TPSHIPNAMEPIRATE00_JAYSCACHE                                54252
#define IDGS_TPSHIPNAMEPIRATE00_KAISERMAX                                54253
#define IDGS_TPSHIPNAMEPIRATE00_KALAMAZOO                                54254
#define IDGS_TPSHIPNAMEPIRATE00_KILLERBEE                                54255
#define IDGS_TPSHIPNAMEPIRATE00_MACE                                     54256
#define IDGS_TPSHIPNAMEPIRATE00_MAGENTA                                  54257
#define IDGS_TPSHIPNAMEPIRATE00_MARSALA                                  54258
#define IDGS_TPSHIPNAMEPIRATE00_MAURICE                                  54259
#define IDGS_TPSHIPNAMEPIRATE00_MAYONSPIRIT                              54260
#define IDGS_TPSHIPNAMEPIRATE00_MERCENARYSTAR                            54261
#define IDGS_TPSHIPNAMEPIRATE00_MIKEYSTROVE                              54262
#define IDGS_TPSHIPNAMEPIRATE00_MINERVA                                  54263
#define IDGS_TPSHIPNAMEPIRATE00_MINIMERCENARY                            54264
#define IDGS_TPSHIPNAMEPIRATE00_MONGOOSE                                 54265
#define IDGS_TPSHIPNAMEPIRATE00_NEMESIS                                  54266
#define IDGS_TPSHIPNAMEPIRATE00_NIGHTRAMBLER                             54267
#define IDGS_TPSHIPNAMEPIRATE00_NYMPH                                    54268
#define IDGS_TPSHIPNAMEPIRATE00_OBLAIRSTREASURE                          54269
#define IDGS_TPSHIPNAMEPIRATE00_ROYALDOLPHIN                             54270
#define IDGS_TPSHIPNAMEPIRATE00_SALTYBOB                                 54271
#define IDGS_TPSHIPNAMEPIRATE00_SALTYJACK                                54272
#define IDGS_TPSHIPNAMEPIRATE00_SANCTUARY                                54273
#define IDGS_TPSHIPNAMEPIRATE00_SAUCYMARE                                54274
#define IDGS_TPSHIPNAMEPIRATE00_SAUCYMARY                                54275
#define IDGS_TPSHIPNAMEPIRATE00_SCOWLER                                  54276
#define IDGS_TPSHIPNAMEPIRATE00_SCURVY                                   54277
#define IDGS_TPSHIPNAMEPIRATE00_SEASPARROW                               54278
#define IDGS_TPSHIPNAMEPIRATE00_SERPENT                                  54279
#define IDGS_TPSHIPNAMEPIRATE00_SHANNON                                  54280
#define IDGS_TPSHIPNAMEPIRATE00_SHRIKE                                   54281
#define IDGS_TPSHIPNAMEPIRATE00_SISTERS                                  54282
#define IDGS_TPSHIPNAMEPIRATE00_SNAPDRAGON                               54283
#define IDGS_TPSHIPNAMEPIRATE00_SPACECOWBOY                              54284
#define IDGS_TPSHIPNAMEPIRATE00_SPEEDYRETURN                             54285
#define IDGS_TPSHIPNAMEPIRATE00_SPIKERATTLER                             54286
#define IDGS_TPSHIPNAMEPIRATE00_STILETTO                                 54287
#define IDGS_TPSHIPNAMEPIRATE00_STINGER                                  54288
#define IDGS_TPSHIPNAMEPIRATE00_SULTANSDREAM                             54289
#define IDGS_TPSHIPNAMEPIRATE00_SWIFT                                    54290
#define IDGS_TPSHIPNAMEPIRATE00_THEBIGSCORE                              54291
#define IDGS_TPSHIPNAMEPIRATE00_THEGENERALSTORE                          54292
#define IDGS_TPSHIPNAMEPIRATE00_THELUCKYBREAK                            54293
#define IDGS_TPSHIPNAMEPIRATE00_THESECRETROOM                            54294
#define IDGS_TPSHIPNAMEPIRATE00_VENOM                                    54295
#define IDGS_TPSHIPNAMEPIRATE00_VIPER                                    54296
#define IDGS_TPSHIPNAMEPIRATE00_WARRIOR                                  54297
#define IDGS_TPSHIPNAMEPIRATE00_WASP                                     54298
#define IDGS_TPSHIPNAMEPIRATE00_WHITECOUNT                               54299
