// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPSHIPNAMEPROCYON00_ARCTICFOX                               54400
#define IDGS_TPSHIPNAMEPROCYON00_ASKOLD                                  54401
#define IDGS_TPSHIPNAMEPROCYON00_ASSAULTLANCE                            54402
#define IDGS_TPSHIPNAMEPROCYON00_ATROPO                                  54403
#define IDGS_TPSHIPNAMEPROCYON00_BAKKAL                                  54404
#define IDGS_TPSHIPNAMEPROCYON00_BALISAR                                 54405
#define IDGS_TPSHIPNAMEPROCYON00_BALLARAT                                54406
#define IDGS_TPSHIPNAMEPROCYON00_BARRIER                                 54407
#define IDGS_TPSHIPNAMEPROCYON00_BATAVIA                                 54408
#define IDGS_TPSHIPNAMEPROCYON00_BATTLEMOON                              54409
#define IDGS_TPSHIPNAMEPROCYON00_BLACKCLOUD                              54410
#define IDGS_TPSHIPNAMEPROCYON00_BLAZEKNIGHT                             54411
#define IDGS_TPSHIPNAMEPROCYON00_BOGATYR                                 54412
#define IDGS_TPSHIPNAMEPROCYON00_BOREALFOX                               54413
#define IDGS_TPSHIPNAMEPROCYON00_BREATHOFRATEC                           54414
#define IDGS_TPSHIPNAMEPROCYON00_BRIGHTGOZARIAN                          54415
#define IDGS_TPSHIPNAMEPROCYON00_CANIS                                   54416
#define IDGS_TPSHIPNAMEPROCYON00_CANOPUS                                 54417
#define IDGS_TPSHIPNAMEPROCYON00_CASCO                                   54418
#define IDGS_TPSHIPNAMEPROCYON00_CHAZMA                                  54419
#define IDGS_TPSHIPNAMEPROCYON00_CHICORA                                 54420
#define IDGS_TPSHIPNAMEPROCYON00_CHTHUGASTAR                             54421
#define IDGS_TPSHIPNAMEPROCYON00_CONQUERORSUN                            54422
#define IDGS_TPSHIPNAMEPROCYON00_CONQUEST                                54423
#define IDGS_TPSHIPNAMEPROCYON00_CORRUPTION                              54424
#define IDGS_TPSHIPNAMEPROCYON00_CRESCENTBEAR                            54425
#define IDGS_TPSHIPNAMEPROCYON00_DARING                                  54426
#define IDGS_TPSHIPNAMEPROCYON00_DARKPHOENIX                             54427
#define IDGS_TPSHIPNAMEPROCYON00_DARKPRINCE                              54428
#define IDGS_TPSHIPNAMEPROCYON00_DECAY                                   54429
#define IDGS_TPSHIPNAMEPROCYON00_DESTROYER                               54430
#define IDGS_TPSHIPNAMEPROCYON00_DICTATOR                                54431
#define IDGS_TPSHIPNAMEPROCYON00_DIPLOMACY                               54432
#define IDGS_TPSHIPNAMEPROCYON00_DRAGON                                  54433
#define IDGS_TPSHIPNAMEPROCYON00_ECLIPSE                                 54434
#define IDGS_TPSHIPNAMEPROCYON00_ENDURANCE                               54435
#define IDGS_TPSHIPNAMEPROCYON00_ENTROPY                                 54436
#define IDGS_TPSHIPNAMEPROCYON00_ERIDANI                                 54437
#define IDGS_TPSHIPNAMEPROCYON00_ESK                                     54438
#define IDGS_TPSHIPNAMEPROCYON00_EVENTHORIZON                            54439
#define IDGS_TPSHIPNAMEPROCYON00_FASTCURRENT                             54440
#define IDGS_TPSHIPNAMEPROCYON00_FEAR                                    54441
#define IDGS_TPSHIPNAMEPROCYON00_FIREWYVERN                              54442
#define IDGS_TPSHIPNAMEPROCYON00_FLAREPANTHER                            54443
#define IDGS_TPSHIPNAMEPROCYON00_FOCA                                    54444
#define IDGS_TPSHIPNAMEPROCYON00_FORMIDABLE                              54445
#define IDGS_TPSHIPNAMEPROCYON00_FUROR                                   54446
#define IDGS_TPSHIPNAMEPROCYON00_GALATICCORE                             54447
#define IDGS_TPSHIPNAMEPROCYON00_GARGANTUAN                              54448
#define IDGS_TPSHIPNAMEPROCYON00_GLORYTAKER                              54449
#define IDGS_TPSHIPNAMEPROCYON00_GROM                                    54450
#define IDGS_TPSHIPNAMEPROCYON00_ICELANCE                                54451
#define IDGS_TPSHIPNAMEPROCYON00_ICEWOLF                                 54452
#define IDGS_TPSHIPNAMEPROCYON00_IRONDUKE                                54453
#define IDGS_TPSHIPNAMEPROCYON00_KEOKUK                                  54454
#define IDGS_TPSHIPNAMEPROCYON00_LAAR                                    54455
#define IDGS_TPSHIPNAMEPROCYON00_LAIRCON                                 54456
#define IDGS_TPSHIPNAMEPROCYON00_MAJORIS                                 54457
#define IDGS_TPSHIPNAMEPROCYON00_MJOLNIR                                 54458
#define IDGS_TPSHIPNAMEPROCYON00_NALDERA                                 54459
#define IDGS_TPSHIPNAMEPROCYON00_NAVARIN                                 54460
#define IDGS_TPSHIPNAMEPROCYON00_NEMESIS                                 54461
#define IDGS_TPSHIPNAMEPROCYON00_NEUTRONSTAR                             54462
#define IDGS_TPSHIPNAMEPROCYON00_NIGHTPRINCE                             54463
#define IDGS_TPSHIPNAMEPROCYON00_NIGHTSWORD                              54464
#define IDGS_TPSHIPNAMEPROCYON00_NOVA                                    54465
#define IDGS_TPSHIPNAMEPROCYON00_ORIONIS                                 54466
#define IDGS_TPSHIPNAMEPROCYON00_PRIDE                                   54467
#define IDGS_TPSHIPNAMEPROCYON00_PRIMALBROOD                             54468
#define IDGS_TPSHIPNAMEPROCYON00_RETRIBUTION                             54469
#define IDGS_TPSHIPNAMEPROCYON00_REVENGE                                 54470
#define IDGS_TPSHIPNAMEPROCYON00_ROGOV                                   54471
#define IDGS_TPSHIPNAMEPROCYON00_RURIK                                   54472
#define IDGS_TPSHIPNAMEPROCYON00_RYGAN                                   54473
#define IDGS_TPSHIPNAMEPROCYON00_SETVAR                                  54474
#define IDGS_TPSHIPNAMEPROCYON00_SHADOWFURY                              54475
#define IDGS_TPSHIPNAMEPROCYON00_SHATTERLYNX                             54476
#define IDGS_TPSHIPNAMEPROCYON00_SIRIUS                                  54477
#define IDGS_TPSHIPNAMEPROCYON00_SMOKEEAGLE                              54478
#define IDGS_TPSHIPNAMEPROCYON00_SNOWBOAR                                54479
#define IDGS_TPSHIPNAMEPROCYON00_SPEAR                                   54480
#define IDGS_TPSHIPNAMEPROCYON00_STARDRAGON                              54481
#define IDGS_TPSHIPNAMEPROCYON00_STARSPEAR                               54482
#define IDGS_TPSHIPNAMEPROCYON00_STEALTH                                 54483
#define IDGS_TPSHIPNAMEPROCYON00_STEELAURORA                             54484
#define IDGS_TPSHIPNAMEPROCYON00_STELLARFLARE                            54485
#define IDGS_TPSHIPNAMEPROCYON00_STORM                                   54486
#define IDGS_TPSHIPNAMEPROCYON00_STORMEAGLE                              54487
#define IDGS_TPSHIPNAMEPROCYON00_STORMLION                               54488
#define IDGS_TPSHIPNAMEPROCYON00_STRIKER                                 54489
#define IDGS_TPSHIPNAMEPROCYON00_SUPERNOVA                               54490
#define IDGS_TPSHIPNAMEPROCYON00_TRIESTE                                 54491
#define IDGS_TPSHIPNAMEPROCYON00_URSA                                    54492
#define IDGS_TPSHIPNAMEPROCYON00_URU                                     54493
#define IDGS_TPSHIPNAMEPROCYON00_VARIAG                                  54494
#define IDGS_TPSHIPNAMEPROCYON00_VENDETTA                                54495
#define IDGS_TPSHIPNAMEPROCYON00_WARBROOD                                54496
#define IDGS_TPSHIPNAMEPROCYON00_WHITEFURY                               54497
#define IDGS_TPSHIPNAMEPROCYON00_ZARA                                    54498
#define IDGS_TPSHIPNAMEPROCYON00_ZEDDEMORE                               54499
