// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_CARGO                     55300
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_CLOAKINGGENERATOR         55301
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_ENGINES                   55302
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_LOWERDECKGUNS             55303
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_MAXVELOCITY               55304
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_MUNITIONS                 55305
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_POWERTRANSFORMERENGINES    55306
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_POWERTRANSFORMERGUNS      55307
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_RUDDERLINKAGE             55308
#define IDGS_TPSPEECHEVENTSCRITICALSECTION_HIT_SPOTTEREQUIPMENT          55309
