// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPTEAMNAMES_22ND_CRUISER_SQD                                55600
#define IDGS_TPTEAMNAMES_32ND_STRIKE_FLOTILLA                            55601
#define IDGS_TPTEAMNAMES_350TH_PURSUIT_FLOTILLA                          55602
#define IDGS_TPTEAMNAMES_47TH_FAST_ATTACK                                55603
#define IDGS_TPTEAMNAMES_73RD_RECON_FLOTILLA                             55604
#define IDGS_TPTEAMNAMES_ATTACKFORCE_GAMMA                               55605
#define IDGS_TPTEAMNAMES_ATTACKFORCE_OMEGA                               55606
#define IDGS_TPTEAMNAMES_BATTLEFORCE_ALPHA                               55607
#define IDGS_TPTEAMNAMES_BATTLEFORCE_DELTA                               55608
#define IDGS_TPTEAMNAMES_CIVILIAN                                        55609
#define IDGS_TPTEAMNAMES_CIVILIAN1                                       55610
#define IDGS_TPTEAMNAMES_FENRAS_COMMAND_FLEET                            55611
#define IDGS_TPTEAMNAMES_FRAKES_PRIVATEERS                               55612
#define IDGS_TPTEAMNAMES_FRASERS_RAIDERS                                 55613
#define IDGS_TPTEAMNAMES_GALDRIN_FRIGATE_SQD                             55614
#define IDGS_TPTEAMNAMES_GUARDFLEET_BETA                                 55615
#define IDGS_TPTEAMNAMES_GUARDFLEET_ZETA                                 55616
#define IDGS_TPTEAMNAMES_IRONCLAD                                        55617
#define IDGS_TPTEAMNAMES_IRONCLAD1                                       55618
#define IDGS_TPTEAMNAMES_IRON_RAIDERS                                    55619
#define IDGS_TPTEAMNAMES_JACKSONS_FIGHTERS                               55620
#define IDGS_TPTEAMNAMES_NAVY                                            55621
#define IDGS_TPTEAMNAMES_NAVY1                                           55622
#define IDGS_TPTEAMNAMES_NONBUDDY_PLAYER                                 55623
#define IDGS_TPTEAMNAMES_PIRATES                                         55624
#define IDGS_TPTEAMNAMES_PIRATES1                                        55625
#define IDGS_TPTEAMNAMES_PRIVATEERS                                      55626
#define IDGS_TPTEAMNAMES_PRIVATEERS1                                     55627
#define IDGS_TPTEAMNAMES_PROCYON                                         55628
#define IDGS_TPTEAMNAMES_PROCYON1                                        55629
#define IDGS_TPTEAMNAMES_ROGUE_NAVY                                      55630
#define IDGS_TPTEAMNAMES_ROGUE_NAVY1                                     55631
#define IDGS_TPTEAMNAMES_ROGUE_PROCYON                                   55632
#define IDGS_TPTEAMNAMES_ROGUE_PROCYON1                                  55633
#define IDGS_TPTEAMNAMES_SEWARDS_ROGUES                                  55634
#define IDGS_TPTEAMNAMES_SWABBIE_COLLECTIVE                              55635
#define IDGS_TPTEAMNAMES_TEAM_1                                          55636
#define IDGS_TPTEAMNAMES_TEAM_2                                          55637
#define IDGS_TPTEAMNAMES_TEAM_3                                          55638
#define IDGS_TPTEAMNAMES_TEAM_4                                          55639
#define IDGS_TPTEAMNAMES_TEAM_5                                          55640
#define IDGS_TPTEAMNAMES_TEAM_6                                          55641
#define IDGS_TPTEAMNAMES_TEAM_7                                          55642
#define IDGS_TPTEAMNAMES_TEAM_8                                          55643
