// Generated on: 9/5/2002 12:25:01 PM
#define IDGS_TPTOOLTIPSEX_COMPASS_MAPSCREEN_CLOSED                       55800
#define IDGS_TPTOOLTIPSEX_COMPASS_MAPSCREEN_OPEN                         55801
#define IDGS_TPTOOLTIPSEX_MAINBAR_PRIMARY_SHIP_COMBAT_BAR                55802
#define IDGS_TPTOOLTIPSEX_MAINBAR_PRIMARY_SHIP_HEALTH_BAR                55803
#define IDGS_TPTOOLTIPSEX_MAINBAR_PRIMARY_SHIP_SAILPOWER_BAR             55804
#define IDGS_TPTOOLTIPSEX_OPTIONBAR_BOARD                                55805
#define IDGS_TPTOOLTIPSEX_OPTIONBAR_CLOAK                                55806
#define IDGS_TPTOOLTIPSEX_OPTIONBAR_UNBOARD                              55807
#define IDGS_TPTOOLTIPSEX_OPTIONBAR_UNCLOAK                              55808
#define IDGS_TPTOOLTIPSEX_OPTIONBAR_UNGRAPPLE                            55809
#define IDGS_TPTOOLTIPSEX_SHIPNAMEBAR                                    55810
#define IDGS_TPTOOLTIPSEX_WEAPONBAR_CARRONAID_HEAVY                      55811
#define IDGS_TPTOOLTIPSEX_WEAPONBAR_CARRONAID_LIGHT                      55812
#define IDGS_TPTOOLTIPSEX_WEAPONBAR_CARRONAID_MEDIUM                     55813
