// Generated on: 9/8/2002 5:31:43 PM
#define IDGS_TPTOOLTIPS_CHATBAR                                          55700
#define IDGS_TPTOOLTIPS_COMPASSWINDOW                                    55701
#define IDGS_TPTOOLTIPS_FORMATIONBAR_ATTACKMYTARGET                      55702
#define IDGS_TPTOOLTIPS_FORMATIONBAR_COLUMN                              55703
#define IDGS_TPTOOLTIPS_FORMATIONBAR_CONVOY                              55704
#define IDGS_TPTOOLTIPS_FORMATIONBAR_DIAMOND                             55705
#define IDGS_TPTOOLTIPS_FORMATIONBAR_ECHELONLEFT                         55706
#define IDGS_TPTOOLTIPS_FORMATIONBAR_ECHELONRIGHT                        55707
#define IDGS_TPTOOLTIPS_FORMATIONBAR_HOLDFIRE                            55708
#define IDGS_TPTOOLTIPS_FORMATIONBAR_LINEABREAST                         55709
#define IDGS_TPTOOLTIPS_MAINBAR_ADVANCEDMOVEMENTTYPEBUTTON               55710
#define IDGS_TPTOOLTIPS_MAINBAR_BEGINNERMOVEMENTTYPEBUTTON               55711
#define IDGS_TPTOOLTIPS_MAINBAR_CHATBUTTON                               55712
#define IDGS_TPTOOLTIPS_MAINBAR_FLEETFORMATIONSBUTTON                    55713
#define IDGS_TPTOOLTIPS_MAINBAR_IS_NOT_PAUSED_BUTTON                     55714
#define IDGS_TPTOOLTIPS_MAINBAR_IS_PAUSED_BUTTON                         55715
#define IDGS_TPTOOLTIPS_MAINBAR_PANICBUTTON                              55716
#define IDGS_TPTOOLTIPS_MAINBAR_SHIPICON                                 55717
#define IDGS_TPTOOLTIPS_OPTIONBAR_AI_LOCK_POSITION                       55718
#define IDGS_TPTOOLTIPS_OPTIONBAR_AI_UNLOCK_POSITION                     55719
#define IDGS_TPTOOLTIPS_OPTIONBAR_DOCK_WITH_TENDER                       55720
#define IDGS_TPTOOLTIPS_OPTIONBAR_FOCUS                                  55721
#define IDGS_TPTOOLTIPS_OPTIONBAR_GRAPPLE                                55722
#define IDGS_TPTOOLTIPS_OPTIONBAR_HARPOONGRAPPLE                         55723
#define IDGS_TPTOOLTIPS_OPTIONBAR_SETLOBTARGET_GRAVCHARGE                55724
#define IDGS_TPTOOLTIPS_OPTIONBAR_SETLOBTARGET_NOVAMORTAR                55725
#define IDGS_TPTOOLTIPS_OPTIONBAR_SETLOBTARGET_STARMORTAR                55726
#define IDGS_TPTOOLTIPS_OPTIONBAR_STOP                                   55727
#define IDGS_TPTOOLTIPS_OPTIONBAR_TOGGLEATTACKSAILORHULL                 55728
#define IDGS_TPTOOLTIPS_OPTIONBAR_TOGGLEAUTOFIRE                         55729
#define IDGS_TPTOOLTIPS_OPTIONBAR_TOW                                    55730
#define IDGS_TPTOOLTIPS_OPTIONBAR_UNTOW                                  55731
#define IDGS_TPTOOLTIPS_SHIPBAR                                          55732
#define IDGS_TPTOOLTIPS_SPEECHEVENTBAR                                   55733
#define IDGS_TPTOOLTIPS_SPEEDSETTING_0                                   55734
#define IDGS_TPTOOLTIPS_SPEEDSETTING_1                                   55735
#define IDGS_TPTOOLTIPS_SPEEDSETTING_2                                   55736
#define IDGS_TPTOOLTIPS_SPEEDSETTING_3                                   55737
#define IDGS_TPTOOLTIPS_SPEEDSETTING_NONE                                55738
#define IDGS_TPTOOLTIPS_TALKINGHEADWINDOW                                55739
#define IDGS_TPTOOLTIPS_TOGGLESHIPBARBUTTON                              55740
#define IDGS_TPTOOLTIPS_TOGGLEWEAPONBARBUTTON                            55741
#define IDGS_TPTOOLTIPS_WEAPONBAR                                        55742
#define IDGS_TPTOOLTIPS_WEAPONBAR_CANNON_HEAVY                           55743
#define IDGS_TPTOOLTIPS_WEAPONBAR_CANNON_LIGHT                           55744
#define IDGS_TPTOOLTIPS_WEAPONBAR_CANNON_MEDIUM                          55745
#define IDGS_TPTOOLTIPS_WEAPONBAR_ENGERGYNETLAUNCHER                     55746
#define IDGS_TPTOOLTIPS_WEAPONBAR_FIRELAUNCHER                           55747
#define IDGS_TPTOOLTIPS_WEAPONBAR_GATTLINGGUN                            55748
#define IDGS_TPTOOLTIPS_WEAPONBAR_GRAVITYCHARGE                          55749
#define IDGS_TPTOOLTIPS_WEAPONBAR_HARPOON                                55750
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_DUAL_HEAVY                      55751
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_DUAL_LIGHT                      55752
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_DUAL_MEDIUM                     55753
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_HEAVY                           55754
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_LIGHT                           55755
#define IDGS_TPTOOLTIPS_WEAPONBAR_LANCER_MEDIUM                          55756
#define IDGS_TPTOOLTIPS_WEAPONBAR_NOVAMORTAR                             55757
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_DUAL_HEAVY                   55758
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_DUAL_LIGHT                   55759
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_DUAL_MEDIUM                  55760
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_HEAVY                        55761
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_LIGHT                        55762
#define IDGS_TPTOOLTIPS_WEAPONBAR_PLASMAGUN_MEDIUM                       55763
#define IDGS_TPTOOLTIPS_WEAPONBAR_STARMINE                               55764
#define IDGS_TPTOOLTIPS_WEAPONBAR_STARMORTAR                             55765
#define IDGS_TPTOOLTIPS_WEAPONBAR_TORPEDO                                55766
