// Generated on: 08/09/2002 10:24:56 PM
#define IDGS_TPWORLDNAMES_BASIC_TUTORIAL                                 56000
#define IDGS_TPWORLDNAMES_CREDITS                                        56001
#define IDGS_TPWORLDNAMES_M01                                            56002
#define IDGS_TPWORLDNAMES_M02                                            56003
#define IDGS_TPWORLDNAMES_M03                                            56004
#define IDGS_TPWORLDNAMES_M04                                            56005
#define IDGS_TPWORLDNAMES_M05                                            56006
#define IDGS_TPWORLDNAMES_M06                                            56007
#define IDGS_TPWORLDNAMES_M07                                            56008
#define IDGS_TPWORLDNAMES_M08                                            56009
#define IDGS_TPWORLDNAMES_M09                                            56010
#define IDGS_TPWORLDNAMES_M10                                            56011
#define IDGS_TPWORLDNAMES_M11                                            56012
#define IDGS_TPWORLDNAMES_M12                                            56013
#define IDGS_TPWORLDNAMES_MP_ARENA                                       56014
#define IDGS_TPWORLDNAMES_MP_ARENA_SMALL                                 56015
#define IDGS_TPWORLDNAMES_MP_BASE_WAR                                    56016
#define IDGS_TPWORLDNAMES_MP_BORDER_DISPUTE                              56017
#define IDGS_TPWORLDNAMES_MP_CUSTOM_MAP                                  56018
#define IDGS_TPWORLDNAMES_MP_DIABLO_STRAIT                               56019
#define IDGS_TPWORLDNAMES_MP_IRON_WAR                                    56020
#define IDGS_TPWORLDNAMES_MP_MOUSETRAP                                   56021
#define IDGS_TPWORLDNAMES_MP_NEBULA_WAR                                  56022
#define IDGS_TPWORLDNAMES_MP_STORM_FRONT                                 56023
#define IDGS_TPWORLDNAMES_NONBUDDY_FE_STRING                             56024
#define IDGS_TPWORLDNAMES_SAMPLE                                         56025
#define IDGS_TPWORLDNAMES_SCEN_AMBUSH                                    56026
#define IDGS_TPWORLDNAMES_SCEN_BAYLES_STAND                              56027
#define IDGS_TPWORLDNAMES_SCEN_CONVOY_RAID                               56028
#define IDGS_TPWORLDNAMES_SCEN_LOCUSTS                                   56029
#define IDGS_TPWORLDNAMES_SCEN_THE_MAW                                   56030
#define IDGS_TPWORLDNAMES_TUTORIAL                                       56031
